// cloneband_harness.cpp — recall-parity + pair-visit-reduction harness for the Y3 minhash pre-gate in
// src/clones.h (findClonesType3). Compiled TWICE by test/clonebandcheck.sh:
//
//   • default            — sketch pre-gate ON (the shipped configuration)
//   • -DCTX_TYPE3_SKETCH_OFF — pre-gate compiled out (every distinct pair reaches the exact Jaccard merge)
//
// and the gate script asserts the two binaries emit BYTE-IDENTICAL Type-3 pair sets (recall parity) while the
// ON build's `jaccardMerges` counter is a small fraction of `distinctPairs` (the perf claim, asserted on a
// deterministic COUNTER, never wall time).
//
// Fixture (all deterministic, generated by a fixed-seed LCG — zero randomness across runs/machines):
//   • 60 "chaff" bodies: same token LENGTH (they pass the length band), a shared prologue/epilogue (so they
//     co-occur in fingerprint buckets and are ENUMERATED as pairs), but pairwise-dissimilar cores
//     (k-gram Jaccard « kType3MinFpJaccard). Baseline behaviour: all C(60,2)=1770 pairs reach the exact
//     Jaccard merge and ALL are rejected there. These are exactly the pairs the sketch gate must kill early.
//   • 2 near-clone pairs (one inserted statement) — genuinely emitted Type-3 pairs; must survive the gate.
//   • 1 BORDERLINE pair: single-token substitutions spaced > kFpGram apart, tuned so the k-gram Jaccard sits
//     just above kType3MinFpJaccard (measured 0.4884) while the LCS-ratio stays ≥ kType3MinSimilarity
//     (measured 0.9259). This is the recall tripwire: a broken/correlated hash family in the sketch would
//     reject it (miss bound at J≈0.49 is ~1e-12 for an honest 128-component minhash — see the bound table
//     beside kSketchMinMatches).
//
// Checks:
//   S1  emitted pair set parity is asserted by the SHELL gate (ON output vs OFF output byte-diff); this
//       harness prints the emitted pairs in a canonical one-line-per-pair form for that diff.
//   S2  both near-clone pairs AND the borderline pair are present (so parity can't pass vacuously on empty).
//   S3  chaff produces zero emitted pairs (no false positive).
//   S4  stats honesty: distinctPairs ≥ 1770 (the chaff really was enumerated + length-band-passed);
//       ON: sketchRejects > 0 and jaccardMerges ≤ distinctPairs/8 (the reduction is REAL);
//       OFF: sketchRejects == 0 and jaccardMerges == distinctPairs (the baseline really is exact-everywhere).
//   S5  determinism: two in-process runs byte-identical (members + similarity + stats).
//
// Exit 0 = all pass; nonzero = failure (messages on stdout). Touches only files under argv[1].

#include "../src/clones.h"

#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>

using namespace ctx;

static int g_fail = 0;
static void check( bool cond, const char* msg )
{
    std::printf( "  %s  %s\n", cond ? "PASS" : "FAIL", msg );
    if( !cond ) g_fail = 1;
}

// write `src` to dir/name, return its absolute path + byte size.
static std::pair<std::string, std::uint32_t> writeFile( const std::string& dir, const char* name, const std::string& src )
{
    const std::string path = dir + "/" + name;
    std::FILE* fp = std::fopen( path.c_str(), "wb" );
    if( fp ) { std::fwrite( src.data(), 1, src.size(), fp ); std::fclose( fp ); }
    return { path, std::uint32_t( src.size() ) };
}

// append a whole-file function symbol (body == [0,size)) to ing.
static void addWholeFileFn( IngestResult& ing, const std::string& path, std::uint32_t size )
{
    const std::uint32_t fileId = std::uint32_t( ing.files.size() );
    ing.files.push_back( path );
    Symbol s;
    s.id           = NodeId( ing.symbols.size() );
    s.kind         = SymKind::Function;
    s.fileId       = fileId;
    s.line         = 1;
    s.sigStartByte = 0;
    s.sigEndByte   = 0;       // body region = [0, size) → whole file is normalized
    s.endByte      = size;    // endByte > sigEndByte ⇒ passes the "real body" gate
    s.name         = std::string( "fn" ) + std::to_string( s.id );
    ing.symbols.push_back( std::move( s ) );
}

// tiny fixed-seed LCG (Numerical Recipes constants) — the fixture's ONLY "variation" source, fully deterministic.
static std::uint32_t lcgNext( std::uint32_t& st ) { st = st * 1664525u + 1013904223u; return st >> 16; }

// one chaff body: shared prologue + epilogue (co-bucketing grams — ALL chaff bodies land in those buckets and
// get pairwise-ENUMERATED) around a per-body core of 150 LCG-drawn single-char operator tokens (operators survive
// normalization verbatim, unlike identifiers/numbers). Every 5-gram window in the core mixes 5 draws from a
// 16-symbol alphabet (16^5 ≈ 1 M window values vs ~150 windows per body) ⇒ cross-body shared core grams ≈ 0 ⇒
// pairwise k-gram Jaccard ≈ (shared prologue+epilogue grams)/union « kType3MinFpJaccard, and the LCS-ratio of two
// LCG cores is far below kType3MinSimilarity (no false positive). Every chaff body has the SAME token count ⇒ the
// length band passes ⇒ the pair reaches the pre-gate (the point: these pairs used to pay the exact Jaccard merge).
// The bodies are token soup, not valid C++ — the clone pass normalizes raw text and never parses.
static std::string chaffBody( std::uint32_t seed )
{
    static const char kOps[16] = { '+', '-', '*', '/', '%', '&', '|', '^', '~', '<', '>', '!', '=', '?', ':', '.' };
    std::uint32_t st = seed * 2654435761u + 1u;
    std::string s = "int f( int a, int b, int c )\n{\n    int acc = 0;\n    int lim = 100;\n    ";
    for( int k = 0; k < 150; ++k ) { s += kOps[ lcgNext( st ) & 15 ]; s += ' '; }
    s += "\n    acc = acc + lim;\n    return acc;\n}\n";
    return s;
}

// near-clone pair: big common body, variant inserts ONE extra block → LCS-ratio in [0.80,1) → emitted Type-3.
static std::string nearBody( int salt, bool variant )
{
    std::string s = "int g( int a, int b, int c, int d )\n{\n    int acc = 0;\n";
    for( int k = 0; k < 14; ++k ) s += ( k % 2 == salt % 2 ) ? "    acc = acc + a * b - c + d;\n" : "    acc = acc * d + a - b;\n";
    if( variant ) s += "    if( acc > a ) { acc = acc - b; } else { acc = acc + c; }\n    acc = acc ^ d;\n";
    for( int k = 0; k < 12; ++k ) s += "    acc = acc - c * d + a;\n";
    s += "    return acc;\n}\n";
    return s;
}

// borderline pair: 16 pairwise-DISTINCT statements (distinct (o1,o2) combos, so k-grams do NOT dedup into a
// subset relation); the variant substitutes o1 in 12 of the 16 (substitutions a whole statement — > kFpGram
// tokens — apart, so each kills its own k-gram windows on both sides). MEASURED on this construction (probe
// over normalizeTokens + the same gram hash): k-gram Jaccard = 0.4884 — just above kType3MinFpJaccard = 0.40,
// i.e. inside the bin the recall bound is weakest for — with LCS-ratio = 0.9259 (well above
// kType3MinSimilarity) → the pair is EMITTED by the exact baseline and must survive the sketch gate.
static std::string borderBody( bool variant )
{
    static const char* ops1[] = { "+", "-", "*", "/", "%", "&", "|", "^" };
    static const char* ops2[] = { "<", ">", "<=", ">=", "==", "!=", "<<", ">>" };
    std::string s = "int h( int a, int b, int c )\n{\n    int acc = 0;\n";
    for( int k = 0; k < 16; ++k )
    {
        const char* o1 = ops1[ k % 8 ];
        const char* o2 = ops2[ ( k / 2 ) % 8 ];
        if( variant && ( k % 4 != 3 ) ) o1 = ops1[ ( k + 3 ) % 8 ];   // 12 single-token substitutions
        s += std::string( "    acc = a " ) + o1 + " b " + o2 + " c;\n";
    }
    s += "    return acc;\n}\n";
    return s;
}

int main( int argc, char** argv )
{
    if( argc < 2 ) { std::fprintf( stderr, "usage: %s <tmpdir>\n", argv[0] ); return 2; }
    const std::string dir = argv[1];

    IngestResult ing;

    // 60 chaff bodies → ids 0..59
    for( int i = 0; i < 60; ++i )
    {
        const std::string name = std::string( "chaff" ) + std::to_string( i ) + ".cpp";
        auto [p, sz] = writeFile( dir, name.c_str(), chaffBody( std::uint32_t( i ) + 1u ) );
        addWholeFileFn( ing, p, sz );
    }
    // 2 near-clone pairs → ids {60,61}, {62,63}
    for( int salt = 0; salt < 2; ++salt )
        for( int v = 0; v < 2; ++v )
        {
            const std::string name = std::string( "near" ) + std::to_string( salt ) + ( v ? "b" : "a" ) + ".cpp";
            auto [p, sz] = writeFile( dir, name.c_str(), nearBody( salt, v == 1 ) );
            addWholeFileFn( ing, p, sz );
        }
    // borderline pair → ids {64,65}
    {
        auto [pa, sa] = writeFile( dir, "border_a.cpp", borderBody( false ) );
        addWholeFileFn( ing, pa, sa );
        auto [pb, sb] = writeFile( dir, "border_b.cpp", borderBody( true ) );
        addWholeFileFn( ing, pb, sb );
    }

    const int minTokens = 18;   // the quality-lane floor (kMinCloneTokens) — the Y3 hot configuration

    Type3Stats                    st{};
    const std::vector<CloneGroup> t3 = findClonesType3( ing, minTokens, &st );

    // S1: canonical emit for the shell-side ON-vs-OFF byte-diff (recall parity).
    std::printf( "EMITTED %zu\n", t3.size() );
    for( const CloneGroup& cg : t3 )
        std::printf( "PAIR %u %u %.4f\n", unsigned( cg.members[0] ), unsigned( cg.members[1] ), double( cg.similarity ) );

    // S2: the engineered positives are present (parity can't pass vacuously).
    bool near0 = false, near1 = false, border = false, chaffPair = false;
    for( const CloneGroup& cg : t3 )
    {
        const NodeId x = cg.members[0], y = cg.members[1];
        if( x == 60 && y == 61 ) near0 = true;
        if( x == 62 && y == 63 ) near1 = true;
        if( x == 64 && y == 65 ) border = true;
        if( x < 60 && y < 60 )   chaffPair = true;
    }
    check( near0 && near1, "S2) both near-clone pairs emitted" );
    check( border,         "S2) borderline (fp-Jaccard 0.4884, just above the 0.40 gate) pair emitted — the sketch-gate recall tripwire" );
    check( !chaffPair,     "S3) no chaff pair emitted (no false positive)" );

    // S4: stats honesty — the chaff really was enumerated and length-band-passed, and the configuration under
    // test behaves as claimed (ON: real reduction; OFF: exact merge for every distinct pair).
    std::printf( "STATS cands=%llu raw=%llu distinct=%llu sketchRejects=%llu jaccardMerges=%llu lcs=%llu emitted=%llu\n",
                 (unsigned long long)st.candidateCount, (unsigned long long)st.rawPairVisits, (unsigned long long)st.distinctPairs,
                 (unsigned long long)st.sketchRejects, (unsigned long long)st.jaccardMerges, (unsigned long long)st.lcsRuns,
                 (unsigned long long)st.emittedPairs );
    check( st.distinctPairs >= 1770, "S4) chaff pairs really reached the pre-gate (distinctPairs >= C(60,2))" );
    check( st.emittedPairs == t3.size(), "S4) stats emitted count matches the returned vector" );
#ifdef CTX_TYPE3_SKETCH_OFF
    check( st.sketchRejects == 0, "S4-OFF) pre-gate compiled out: zero sketch rejects" );
    check( st.jaccardMerges == st.distinctPairs, "S4-OFF) every distinct pair reaches the exact Jaccard merge (the baseline is exact-everywhere)" );
#else
    check( st.sketchRejects > 0, "S4-ON) the sketch pre-gate actually fired" );
    check( st.jaccardMerges <= st.distinctPairs / 8, "S4-ON) exact Jaccard merges cut >= 8x by the pre-gate (counter, not wall time)" );
    check( st.sketchRejects + st.jaccardMerges == st.distinctPairs, "S4-ON) every distinct pair is either sketch-rejected or merged (no third path)" );
#endif

    // S5: determinism — a second in-process run is identical in members, similarity, and counters.
    Type3Stats                    st2{};
    const std::vector<CloneGroup> t3b = findClonesType3( ing, minTokens, &st2 );
    bool detOk = ( t3.size() == t3b.size() );
    for( std::size_t i = 0; detOk && i < t3.size(); ++i )
        detOk = ( t3[i].members == t3b[i].members && t3[i].type == t3b[i].type && t3[i].similarity == t3b[i].similarity );
    detOk = detOk && st.rawPairVisits == st2.rawPairVisits && st.distinctPairs == st2.distinctPairs
                  && st.sketchRejects == st2.sketchRejects && st.jaccardMerges == st2.jaccardMerges && st.lcsRuns == st2.lcsRuns;
    check( detOk, "S5) two runs byte-identical (pairs + similarities + all counters)" );

    std::printf( g_fail ? "CLONEBAND HARNESS: FAIL\n" : "CLONEBAND HARNESS: OK\n" );
    return g_fail;
}
