#!/usr/bin/env bash
# docscommandscheck.sh — docs/COMMANDS.md must not drift from the binary's own flag surface.
#
# WHY. docs/COMMANDS.md is GENERATED by docs/docs_commands_build.py from `<bin> --help`. A generated
# document is only trustworthy while something checks that it was regenerated: the failure this gate
# exists to catch is a flag landing (or being renamed, or removed) without the document moving, which
# no compiler and no other gate would notice.
#
# Arms:
#   (A) the generator and the generated document both exist and the generator parses
#   (B) the DRIFT arm — `--check` compares the documented flag set against the binary's, both
#       directions: a flag in --help but not the doc, or in the doc but not --help, is red
#   (C) MUTATION CONTROL for (B) — a fabricated flag is injected into a COPY of the doc and (B) must
#       go red on it. Without this arm, a --check that silently stopped comparing would read as a
#       pass forever; the arm proves the check can still see a difference
#   (D) name agreement — the document's title names the binary it was generated from, so a renamed
#       binary with a stale document is red rather than quietly wrong
#   (E) public-export scrub — EVERY scrub class the generator implements, run over docs/COMMANDS.md
#       AND every docs/captures/*.md, using the generator's OWN predicates (imported, not restated)
#   (F) MUTATION CONTROL for (E) — each class must fire on a synthetic offender, and real output that
#       merely LOOKS like a leak (--hotspots `top=`, community `sym@file.ext` labels, --layout
#       `owner=`) must survive untouched: an over-broad scrub corrupts output, which is worse than
#       the leak because the corruption ships as the tool's answer
#   (G) REGENERATION PARITY — regenerating from the binary plus the newest capture in the tree must
#       reproduce docs/COMMANDS.md byte for byte. Arms (A)-(F) all passed while the shipped doc was
#       built from a capture (and a generator variant) that were never committed — (B) compares flag
#       NAME sets, not content — so the next honest regen silently deleted sample content. Content
#       that cannot be reproduced from the committed tree is content that is already lost
#   (H) ENTRY-RECOGNITION CONTRACT — the one thing (A)-(G) structurally cannot see. A flag whose
#       --help line parse_help fails to recognize vanishes from BOTH sides of arm (B)'s comparison at
#       once (both derive from parse_help), so the sets stay equal and (B) stays green while the flag
#       is absent from the shipped document. This arm imports parse_help and judges it directly,
#       against a pinned ledger of the losses that already exist plus synthetic seam fixtures
#
# Usage:  bash test/docscommandscheck.sh      [RIPWIRE_BIN=path/to/binary]
# Exit:   0 = clean · 1 = at least one arm failed · 2 = usage / missing prerequisite

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${1:-${RIPWIRE_BIN:-$ROOT/build/ripwire}}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"
GEN="$ROOT/docs/docs_commands_build.py"
DOC="$ROOT/docs/COMMANDS.md"
fail=0

ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

# A missing prerequisite must never read as a clean tree. Name it and exit 2 — never 0.
command -v python3 >/dev/null 2>&1 || { printf 'docscommandscheck: python3 missing (gate cannot run)\n'; exit 2; }
[ -x "$BIN" ] || { printf 'docscommandscheck: no binary at %s — build first\n' "$BIN"; exit 2; }

TMP="$( mktemp -d )"
trap 'rm -rf "$TMP"' EXIT

# ── (A) the pieces exist ──────────────────────────────────────────────────────────────────────────
if [ -f "$GEN" ]; then ok "(A) generator present (docs/docs_commands_build.py)"
else no "(A) docs/docs_commands_build.py is missing — COMMANDS.md cannot be regenerated"; fi

if [ -f "$DOC" ]; then ok "(A) generated document present (docs/COMMANDS.md)"
else no "(A) docs/COMMANDS.md is missing — regenerate: python3 docs/docs_commands_build.py --bin $BIN"; fi

if [ -f "$GEN" ] && python3 -c "import ast,sys; ast.parse(open(sys.argv[1]).read())" "$GEN" 2>/dev/null
then ok "(A) generator parses as python3"
else no "(A) generator does not parse as python3"; fi

[ -f "$GEN" ] && [ -f "$DOC" ] || { printf 'docscommandscheck: FAILURES ABOVE\n'; exit 1; }

# ── (B) the drift arm ─────────────────────────────────────────────────────────────────────────────
checkOut="$( python3 "$GEN" --bin "$BIN" --out "$DOC" --check 2>&1 )"
checkRc=$?
if [ "$checkRc" = 0 ]; then
    ok "(B) documented flag set == binary flag set — $( printf '%s' "$checkOut" | tr -d '\n' )"
else
    no "(B) docs/COMMANDS.md has drifted from $( basename "$BIN" ) --help:"
    printf '%s\n' "$checkOut" | sed 's/^/          /'
fi

# ── (C) mutation control — prove (B) can still fail ───────────────────────────────────────────────
# The drift arm compares two sets. A comparison that stopped comparing (a parse that silently yields
# an empty set on both sides, say) would pass forever. Inject a flag that cannot exist in any binary
# into a COPY of the document and require the same invocation to go red.
cp "$DOC" "$TMP/mutated.md"
printf '\n### `--zzz-not-a-real-flag=X`\n\n**Answers:** injected by test/docscommandscheck.sh arm (C).\n' >> "$TMP/mutated.md"
python3 "$GEN" --bin "$BIN" --out "$TMP/mutated.md" --check >"$TMP/mutated.out" 2>&1
if [ $? != 0 ] && grep -q 'zzz-not-a-real-flag' "$TMP/mutated.out"; then
    ok "(C) mutation control — an injected flag makes the drift arm red (the check is live, not inert)"
else
    no "(C) mutation control — an injected flag did NOT make the drift arm red; arm (B) is inert and its PASS means nothing"
    sed 's/^/          /' "$TMP/mutated.out"
fi

# ── (D) the document names the binary it was generated from ───────────────────────────────────────
binName="$( basename "$BIN" )"
docName="$( head -1 "$DOC" | sed -n 's/^# \([^ ]*\) .*/\1/p' )"
if [ -n "$docName" ] && [ "$docName" = "$binName" ]; then
    ok "(D) document title names the binary it documents ($docName)"
elif [ -z "$docName" ]; then
    no "(D) could not read a tool name from the first line of docs/COMMANDS.md"
else
    no "(D) docs/COMMANDS.md documents '$docName' but the binary is '$binName' — regenerate: python3 docs/docs_commands_build.py --bin $BIN"
fi

# ── (E) public-export scrub — EVERY class the generator claims to scrub, on BOTH documents ────────
# The old arm ran two of the generator's six substitution classes (home path, coordinate) and only
# over COMMANDS.md. That left the two classes that actually leaked a person — EMAIL and the ownership
# identity attributes — unchecked by anything, and it never looked at the capture at all, even though
# the capture is a committed document that COMMANDS.md lifts its samples from: a leak there ships
# twice and was gated zero times.
#
# The predicates below are IMPORTED from the generator, not restated here. That is the point: a gate
# that re-spells its subject's regexes tests its own copy, and a widened scrub with a stale gate reads
# green. `find_address` in particular carries the discriminator that keeps ripwire's own
# `symbol@file.ext` community labels from being mistaken for addresses — restating it by hand here
# would have this arm red on correct output.
cat > "$TMP/scrubarm.py" <<'PY'
import glob, os, re, sys

ROOT = sys.argv[1]
sys.path.insert( 0, os.path.join( ROOT, 'docs' ) )
try:
    import docs_commands_build as gen
except ImportError as exc:
    print( 'IMPORT_FAIL %s' % exc )
    sys.exit( 0 )

# spelled with a class so this gate does not itself contain the literal it hunts for
HOME = re.compile( r'/[Uu]sers/' )
CLASSES = (
    ( 'absolute home path',        lambda ln: HOME.search( ln ) ),
    ( 'temp/scratch path',         lambda ln: gen.TMP_PATH.search( ln ) ),
    ( 'internal coordinate shape', lambda ln: gen.COORD.search( ln ) ),
    ( 'internal document name',    lambda ln: gen.INTERNAL_DOC.search( ln ) ),
    ( 'email address',             lambda ln: gen.find_address( ln ) ),
)

targets = [ os.path.join( ROOT, 'docs', 'COMMANDS.md' ) ]
targets += sorted( glob.glob( os.path.join( ROOT, 'docs', 'captures', '*.md' ) ) )
print( 'SCANNED %d' % len( targets ) )
for path in targets:
    rel = os.path.relpath( path, ROOT )
    for i, line in enumerate( open( path, encoding = 'utf-8', errors = 'replace' ), 1 ):
        for label, hit in CLASSES:
            if hit( line ):
                print( 'HIT %s:%d: %s: %s' % ( rel, i, label, line.strip()[ :100 ] ) )
                break
PY
python3 "$TMP/scrubarm.py" "$ROOT" > "$TMP/scrub" 2>&1
scannedCount="$( grep '^SCANNED ' "$TMP/scrub" | awk '{print $2}' )"
if grep -q '^IMPORT_FAIL' "$TMP/scrub"; then
    no "(E) could not import the scrub predicates from docs/docs_commands_build.py — the arm cannot run: $( grep '^IMPORT_FAIL' "$TMP/scrub" )"
elif [ "${scannedCount:-0}" -lt 2 ]; then
    no "(E) scanned only ${scannedCount:-0} document(s) — COMMANDS.md plus at least one docs/captures/*.md is expected; a near-empty scan passes vacuously"
elif grep -q '^HIT ' "$TMP/scrub"; then
    no "(E) shipped document(s) trip the public-export scrub in $( grep -c '^HIT ' "$TMP/scrub" ) place(s):"
    grep '^HIT ' "$TMP/scrub" | sed 's/^HIT /          /'
else
    ok "(E) all $scannedCount shipped document(s) clean on every scrub class (home path, temp path, coordinate, internal doc name, address)"
fi

# ── (F) mutation control for (E) — prove the scrub arm can still see a leak ────────────────────────
# Same reasoning as (C): a predicate that silently stopped matching would make (E) a permanent PASS.
# Feed each class a synthetic offender through the SAME imported predicates and require every one to
# fire. This does not touch the real documents.
cat > "$TMP/scrubmutate.py" <<'PY'
import os, re, sys

ROOT = sys.argv[1]
sys.path.insert( 0, os.path.join( ROOT, 'docs' ) )
import docs_commands_build as gen

HOME = re.compile( r'/[Uu]sers/' )
PROBES = (
    ( 'absolute home path',        '/' + 'Users' + '/someone/checkout/src', lambda ln: HOME.search( ln ) ),
    ( 'temp/scratch path',         '/private/tmp/ripwire_showcase_ab12/aux', lambda ln: gen.TMP_PATH.search( ln ) ),
    ( 'internal coordinate shape', 'see ' + '§' + 'B12.9 of the round plan',  lambda ln: gen.COORD.search( ln ) ),
    ( 'internal document name',    'PLAN' + '_something.md',                lambda ln: gen.INTERNAL_DOC.search( ln ) ),
    ( 'email address',             'top="someone@example.com"',             lambda ln: gen.find_address( ln ) ),
)
# and the NEGATIVE controls: real output the scrub must NOT claim as a leak (the over-scrub failure).
NEGATIVES = (
    ( 'hotspots symbol name',  '<f p="./src/main.cpp" churn="5" ccx="3311" top="main" top_ccx="376"/>' ),
    ( 'community label',       '<community id="952" label="./src::str@ingest.cpp:887:55947"/>' ),
    ( 'layout field owner',    '<field name="id" type="uint32_t" owner="Symbol" rel="0"/>' ),
)
bad = 0
for label, probe, hit in PROBES:
    if not hit( probe ):
        print( 'DEAD %s: predicate did not fire on a synthetic offender' % label ); bad += 1
for label, line in NEGATIVES:
    scrubbed = gen.scrub_emails( gen.scrub_author_attrs( line ) )
    if scrubbed != line:
        print( 'OVERSCRUB %s: real output was rewritten: %s -> %s' % ( label, line, scrubbed ) ); bad += 1
# and the one that MUST be rewritten, so the gate is not merely proving the scrub is a no-op
ownerRow = '<f p="./SECURITY.md" authors="2" bf="0" top="someone@example.com" share="0.50"/>'
if 'someone@example.com' in gen.scrub_emails( gen.scrub_author_attrs( ownerRow ) ):
    print( 'DEAD ownership row: an address on a share= row survived the scrub' ); bad += 1
print( 'MUTATE %d' % bad )
PY
mutateOut="$( python3 "$TMP/scrubmutate.py" "$ROOT" 2>&1 )"
if printf '%s' "$mutateOut" | grep -q '^MUTATE 0$'; then
    ok "(F) mutation control — every scrub class fires on a synthetic leak, and real output (hotspots top=, community labels, layout owner=) survives untouched"
else
    no "(F) mutation control failed — the scrub is inert or over-broad:"
    printf '%s\n' "$mutateOut" | sed 's/^/          /'
fi

# ── (G) regeneration parity — the doc must be reproducible from the COMMITTED capture ─────────────
# The failure this arm exists to catch (found 2026-08-08): docs/COMMANDS.md had been regenerated
# from a FRESHER capture — and a modified generator — that were never committed, so the sole
# committed capture predated the doc's own sample rows (ev=/humps=/locals= appeared in the doc but
# in no capture on disk), and an honest regen DELETED them. The direct assertion is
# reproducibility: the generator is deterministic over (binary --help, newest capture), so a regen
# into a scratch path must give back the shipped doc byte for byte. This subsumes any "is the
# capture newer than attribute X" heuristic — a capture too old to know an attribute the doc's
# samples carry cannot reproduce the doc, and goes red here, as does an uncommitted generator edit.
regenOut="$( python3 "$GEN" --bin "$BIN" --out "$TMP/regen.md" 2>&1 )"
regenRc=$?
if [ "$regenRc" != 0 ]; then
    no "(G) regeneration failed (exit $regenRc) — cannot prove docs/COMMANDS.md is reproducible from the tree:"
    printf '%s\n' "$regenOut" | sed 's/^/          /'
elif diff -q "$DOC" "$TMP/regen.md" >/dev/null; then
    ok "(G) docs/COMMANDS.md is byte-identical to a regeneration from the newest capture in the tree"
else
    no "(G) docs/COMMANDS.md does NOT match a regeneration from the newest capture in the tree — the doc was built from a capture or generator that is not committed, or moved without a regen. First differing lines:"
    diff "$DOC" "$TMP/regen.md" | head -12 | sed 's/^/          /'
fi

# ── (H) ENTRY-RECOGNITION CONTRACT — the generator's glue, unit-tested against parse_help itself ──
# The failure this arm exists to catch SHIPPED ONCE ALREADY, and was hand-patched one commit before
# this arm was written (658c440, which fixed the offending seams in src/cli.h and regenerated
# docs/COMMANDS.md but touched neither the generator nor this gate — so nothing stops the next one).
#
# docs_commands_build.parse_help used to recognize a flag entry only at "flag + TWO OR MORE spaces"
# (or end-of-line). A line whose flag was separated from its prose by a SINGLE space did not match; it
# fell through and was appended as continuation prose onto the PREVIOUS entry, or — if it was the
# first entry in its section — was dropped outright. Either way the flag vanished from `sections`:
# silently, no error, exit 0.
#
# Arms (A)-(G) cannot see this class of bug. Arm (B) is the drift check, and BOTH sides of its
# comparison derive from parse_help: `binary_flags()` reads the parsed sections, and
# `documented_flags()` reads the `### ` headings of a document that parse_help itself wrote. A flag
# the parser loses disappears from both sides at once, so the sets stay equal and (B) is green.
#
# THE LEDGER WAS TWELVE, NOW ZERO. At 1dc7b01, twelve flags were lost by the parser — including the
# flagship verbs --merge-scout, --note-add and --plan-lanes, and -h/-v themselves — across three
# DISTINCT shapes: a single-space seam, a space INSIDE the value spec (--note-add="TARGET: text"),
# and two flags sharing one line (--limit=N --offset=M, and the "|"/"/"-alternated
# --grep-context=N | --grep-before=N / --grep-after=N). parse_help's entry/prose boundary
# (`_spec_end` in docs/docs_commands_build.py) now closes all three at once: a spec is a chain of
# dash-tokens — extended across `|`, `/`, `,`, or a bare space, with one embedded `"..."` chunk
# allowed inside a token — and the chain simply stops at the first whitespace-separated token that
# does not itself start with a dash, whatever the width of that whitespace. So THE LEDGER BELOW IS
# EMPTY. It stays a live pinned set, exactly like --arch --baseline's debt ledger: a THIRTEENTH loss
# (the 658c440 bug happening again, in a shape `_spec_end` does not yet cover) is red immediately, and
# the moment is right to add it to LEDGER and open a fix, not to let (H1) go quietly green over it.
# The lost flags are printed on every run rather than merely counted: a number nobody can read is not
# a disclosure.
cat > "$TMP/entryarm.py" <<'PY'
import os, re, subprocess, sys

ROOT, BIN = sys.argv[1], sys.argv[2]
sys.path.insert( 0, os.path.join( ROOT, 'docs' ) )
import docs_commands_build as gen

bad = 0
def ok( m ): print( "  PASS  %s" % m )
def no( m ):
    global bad; bad = 1; print( "  FAIL  %s" % m )

# KNOWN-LOST. Empty since the parse_help fix that closed the seam/quoted-value/two-flags-per-line
# shapes (see the block comment above). Grow this ONLY in the commit that discovers a new loss, and
# shrink it ONLY in the commit that fixes the parser for that shape — it must never quietly outlive
# the defect it records in either direction.
LEDGER = []

# Identify CANDIDATE entry lines independently of the contract under test. This grabs only the leading
# dash token so a candidate can be named; it deliberately does NOT restate parse_help's own entry
# pattern (arm (E)'s precedent: a gate that re-spells its subject's regex tests its own copy).
LEAD = re.compile( r'^ {4,6}(-\S*)' )

def lost_flags( helpText ):
    """Flags that appear at entry indent in helpText but never reach parse_help's flag set."""
    _pre, sections = gen.parse_help( helpText )
    known = gen.binary_flags( sections )
    out = []
    for line in helpText.split( '\n' ):
        m = LEAD.match( line )
        if not m:
            continue
        flags = gen.normalize_flags( m.group( 1 ) )
        if flags and flags[ 0 ] not in known and flags[ 0 ] not in out:
            out.append( flags[ 0 ] )
    return out

# ── (H1) the ledger, against the real binary ──────────────────────────────────────────────────────
helpText = subprocess.run( [ BIN, '--help' ], capture_output = True, text = True, timeout = 120 ).stdout
live = sorted( lost_flags( helpText ) )
pinned = sorted( LEDGER )
newLoss = [ f for f in live if f not in pinned ]
rescued = [ f for f in pinned if f not in live ]
if newLoss:
    no( "(H1) %d flag(s) newly vanish inside docs_commands_build.parse_help and will be ABSENT from "
        "docs/COMMANDS.md with no error and exit 0: %s" % ( len( newLoss ), ", ".join( newLoss ) ) )
    print( "          the flag's --help line separates it from its prose by a single space, or puts a "
           "space inside its value spec, or shares the line with a second flag." )
    print( "          Fix the seam in src/cli.h (two or more spaces before the prose) and regenerate, "
           "as 658c440 did — do NOT add it to this gate's LEDGER." )
if rescued:
    no( "(H1) %d ledger entr%s no longer lost — the parser was fixed but the ledger was not shrunk in "
        "the same commit: %s" % ( len( rescued ), "y is" if len( rescued ) == 1 else "ies are",
        ", ".join( rescued ) ) )
if not newLoss and not rescued:
    ok( "(H1) parse_help's known loss set is exactly the pinned ledger (%d): %s" % ( len( live ), ", ".join( live ) ) )

# ── (H2) mutation control — prove the detector above can still see a loss, and a non-loss ─────────
# The ORIGINAL positive control put a single-space seam in FIXTURE and required lost_flags to report
# it lost. That fixture is retired: `_spec_end` now closes the seam shape (and the other two) for
# EVERY line at entry indent (4-6 spaces, leading dash) — the spec/prose boundary is total for that
# shape by construction, not a pattern match that happens to cover today's known cases. No text
# satisfying LEAD below can any longer produce a loss, so a fixture built the old way would make (H2)
# red for the wrong reason: not because the detector went inert, but because the shape it used to
# probe is closed. (This is exactly the trap the block comment above warns about — if you are
# re-opening this arm because it went red, re-read that comment before touching LEDGER.)
#
# The replacement targets the SUBTRACTION machinery directly, the way arm (F) feeds a synthetic
# offender straight to an imported predicate instead of hunting for a real leaking document: wrap
# `gen.parse_help` so it silently discards one well-formed entry on the way out — standing in for a
# parser regression exactly like the one 658c440 fixed — and confirm `lost_flags`'s logic (LEAD scrape
# minus `binary_flags(parse_help(...))`) still notices when it is fed that wrapped result. This proves
# liveness without depending on any parseable shape remaining broken, and it stays a valid probe no
# matter how much MORE of `_spec_end`'s grammar future work covers.
FIXTURE = ( "usage: tool <dir>\n"
            "\n"
            "  Section\n"
            "    --foo=X single-space text\n"
            "    --bar=Y  two-space ok\n" )
_pre, secs = gen.parse_help( FIXTURE )
entries = [ e for _t, es in secs for e in es ]
fixtureLost = lost_flags( FIXTURE )

def _lost_flags_against( sections ):
    """lost_flags's own LEAD-scrape-minus-known logic, but against an already-parsed `sections` —
    the seam that lets (H2) inject a regression without a real broken --help shape to feed it."""
    known = gen.binary_flags( sections )
    out = []
    for line in FIXTURE.split( '\n' ):
        m = LEAD.match( line )
        if not m:
            continue
        flags = gen.normalize_flags( m.group( 1 ) )
        if flags and flags[ 0 ] not in known and flags[ 0 ] not in out:
            out.append( flags[ 0 ] )
    return out

regressedSections = [ ( t, [ e for e in es if '--foo' not in e[ 'flags' ] ] ) for t, es in secs ]
mutantLost = _lost_flags_against( regressedSections )
if '--foo' in mutantLost:
    ok( "(H2) mutation control — a parser that silently drops a well-formed entry is caught as a loss "
        "(the detector in (H1) is live, not inert)" )
else:
    no( "(H2) mutation control — a deliberately dropped entry was NOT reported lost; arm (H1)'s PASS "
        "means nothing. mutant lost_flags: %s" % mutantLost )

if fixtureLost == []:
    ok( "(H2) positive-shape proof — the real (unmutated) parser loses nothing in this fixture, "
        "single-space seam included: the shape (H1)'s old ledger pinned is genuinely closed" )
else:
    no( "(H2) the real parser still loses something in this fixture: %s — LEDGER and this fixture "
        "have drifted from what parse_help actually does" % fixtureLost )

barEntry = [ e for e in entries if '--bar' in e[ 'flags' ] ]
if len( barEntry ) == 1 and barEntry[ 0 ][ 'text' ] == 'two-space ok':
    ok( "(H2) negative control — a well-formed two-space entry survives as its own entry with its own prose" )
else:
    no( "(H2) negative control — a well-formed two-space entry did NOT survive intact; parse_help is "
        "broken for the shape the whole document depends on. entries: %s" % [ ( e[ 'spec' ], e[ 'text' ] ) for e in entries ] )

sys.exit( bad )
PY
if python3 "$TMP/entryarm.py" "$ROOT" "$BIN" 2>&1; then :; else fail=1; fi

if [ "$fail" = 0 ]; then printf 'ALL PASS\n'; else printf 'FAILURES ABOVE\n'; fi
exit "$fail"
