#!/usr/bin/env bash
# docscommandscheck.sh — docs/COMMANDS.md must not drift from the binary's own flag surface.
#
# WHY. docs/COMMANDS.md is GENERATED by docs/docs_commands_build.py from `<bin> --help`. A generated
# document is only trustworthy while something checks that it was regenerated: the failure this gate
# exists to catch is a flag landing (or being renamed, or removed) without the document moving, which
# no compiler and no other gate would notice.
#
# Arms:
#   (A) the generator and the generated document both exist and the generator parses
#   (B) the DRIFT arm — `--check` compares the documented flag set against the binary's, both
#       directions: a flag in --help but not the doc, or in the doc but not --help, is red
#   (C) MUTATION CONTROL for (B) — a fabricated flag is injected into a COPY of the doc and (B) must
#       go red on it. Without this arm, a --check that silently stopped comparing would read as a
#       pass forever; the arm proves the check can still see a difference
#   (D) name agreement — the document's title names the binary it was generated from, so a renamed
#       binary with a stale document is red rather than quietly wrong
#   (E) public-export scrub — the generated document carries no absolute home paths and no internal
#       coordinate shapes (the same patterns test/ripwirepubliccheck.sh enforces)
#
# Usage:  bash test/docscommandscheck.sh      [CTXPACK_BIN=path/to/binary]
# Exit:   0 = clean · 1 = at least one arm failed · 2 = usage / missing prerequisite

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${CTXPACK_BIN:-$ROOT/build/ctxpack}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"
GEN="$ROOT/docs/docs_commands_build.py"
DOC="$ROOT/docs/COMMANDS.md"
fail=0

ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

# A missing prerequisite must never read as a clean tree. Name it and exit 2 — never 0.
command -v python3 >/dev/null 2>&1 || { printf 'docscommandscheck: python3 missing (gate cannot run)\n'; exit 2; }
[ -x "$BIN" ] || { printf 'docscommandscheck: no binary at %s — build first\n' "$BIN"; exit 2; }

TMP="$( mktemp -d )"
trap 'rm -rf "$TMP"' EXIT

# ── (A) the pieces exist ──────────────────────────────────────────────────────────────────────────
if [ -f "$GEN" ]; then ok "(A) generator present (docs/docs_commands_build.py)"
else no "(A) docs/docs_commands_build.py is missing — COMMANDS.md cannot be regenerated"; fi

if [ -f "$DOC" ]; then ok "(A) generated document present (docs/COMMANDS.md)"
else no "(A) docs/COMMANDS.md is missing — regenerate: python3 docs/docs_commands_build.py --bin $BIN"; fi

if [ -f "$GEN" ] && python3 -c "import ast,sys; ast.parse(open(sys.argv[1]).read())" "$GEN" 2>/dev/null
then ok "(A) generator parses as python3"
else no "(A) generator does not parse as python3"; fi

[ -f "$GEN" ] && [ -f "$DOC" ] || { printf 'docscommandscheck: FAILURES ABOVE\n'; exit 1; }

# ── (B) the drift arm ─────────────────────────────────────────────────────────────────────────────
checkOut="$( python3 "$GEN" --bin "$BIN" --out "$DOC" --check 2>&1 )"
checkRc=$?
if [ "$checkRc" = 0 ]; then
    ok "(B) documented flag set == binary flag set — $( printf '%s' "$checkOut" | tr -d '\n' )"
else
    no "(B) docs/COMMANDS.md has drifted from $( basename "$BIN" ) --help:"
    printf '%s\n' "$checkOut" | sed 's/^/          /'
fi

# ── (C) mutation control — prove (B) can still fail ───────────────────────────────────────────────
# The drift arm compares two sets. A comparison that stopped comparing (a parse that silently yields
# an empty set on both sides, say) would pass forever. Inject a flag that cannot exist in any binary
# into a COPY of the document and require the same invocation to go red.
cp "$DOC" "$TMP/mutated.md"
printf '\n### `--zzz-not-a-real-flag=X`\n\n**Answers:** injected by test/docscommandscheck.sh arm (C).\n' >> "$TMP/mutated.md"
python3 "$GEN" --bin "$BIN" --out "$TMP/mutated.md" --check >"$TMP/mutated.out" 2>&1
if [ $? != 0 ] && grep -q 'zzz-not-a-real-flag' "$TMP/mutated.out"; then
    ok "(C) mutation control — an injected flag makes the drift arm red (the check is live, not inert)"
else
    no "(C) mutation control — an injected flag did NOT make the drift arm red; arm (B) is inert and its PASS means nothing"
    sed 's/^/          /' "$TMP/mutated.out"
fi

# ── (D) the document names the binary it was generated from ───────────────────────────────────────
binName="$( basename "$BIN" )"
docName="$( head -1 "$DOC" | sed -n 's/^# \([^ ]*\) .*/\1/p' )"
if [ -n "$docName" ] && [ "$docName" = "$binName" ]; then
    ok "(D) document title names the binary it documents ($docName)"
elif [ -z "$docName" ]; then
    no "(D) could not read a tool name from the first line of docs/COMMANDS.md"
else
    no "(D) docs/COMMANDS.md documents '$docName' but the binary is '$binName' — regenerate: python3 docs/docs_commands_build.py --bin $BIN"
fi

# ── (E) public-export scrub of the generated document ─────────────────────────────────────────────
python3 - "$DOC" > "$TMP/scrub" <<'PY'
import re, sys
home  = re.compile( r'/Users/' )
coord = re.compile( r'§A|§B[0-9]|§P[0-9]|V[0-9]-[0-9]|W[0-9]|r[0-9][0-9]-' )
for i, line in enumerate( open( sys.argv[1], encoding = 'utf-8', errors = 'replace' ), 1 ):
    if home.search( line ):
        print( '%d: absolute home path: %s' % ( i, line.strip()[ :100 ] ) )
    elif coord.search( line ):
        print( '%d: internal coordinate shape: %s' % ( i, line.strip()[ :100 ] ) )
PY
if [ -s "$TMP/scrub" ]; then
    no "(E) generated document trips the public-export scrub in $( wc -l < "$TMP/scrub" | tr -d ' ' ) place(s):"
    sed 's/^/          /' "$TMP/scrub"
else
    ok "(E) generated document carries no home paths and no internal coordinate shapes"
fi

if [ "$fail" = 0 ]; then printf 'ALL PASS\n'; else printf 'FAILURES ABOVE\n'; fi
exit "$fail"
