#!/usr/bin/env bash
# fnptrcheck.sh — gate for the fn-pointer/callback binding round (P2-D Rule 2 extended to var→FUNCTION).
#
# The disclosed gap this closes: every graph-count legend said a call through "a callback or function
# pointer ... contributes no edge". Post-round, a call-shaped reference `fn()` whose name matches a LIVE,
# UNAMBIGUOUS var→function binding in the same local scope (or an unclobbered file-scope binding) resolves
# to the bound function — a plain role="call" edge (it IS a real call; only the resolution came from the
# binding, the same trust level as Rule 2 receiver narrowing). Everything uncertain stays edge-less:
#   * a var assigned TWO different functions anywhere in its scope is TOMBSTONED (resolves to NOTHING —
#     not even to a same-named global function, because the binding proves the call goes through the var);
#   * an array/table of function pointers indexed dynamically (`handlers[i]()`) produces NO confident edge;
#   * a lambda-bound var (`auto cb = [](){...}; cb();`) resolves to nothing extra — the lambda's body is
#     already attributed to the enclosing function — and must never produce a FALSE edge.
# Zero false edges is the bar: when in doubt, don't resolve.
#
# The fixture is GENERATED here (self-contained; nothing committed under test/). The global function `fn`
# is the name-collision control: PRE-change, `fn()` inside useDirect/reassigned resolved to it by bare
# name (a false edge — the call goes through the local variable); POST-change the binding dominates.
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/fnptrcheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${1:-${RIPWIRE_BIN:-$ROOT/build/ripwire}}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/fnptrfix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/fnptr.cpp" <<'EOF'
// fn-pointer binding gate fixture — generated by test/fnptrcheck.sh, never committed.
typedef void (*H)();
void alpha() {}
void beta() {}
void helperFn() {}
void fn() {}   // name-collision control: a GLOBAL function named like the local fn-ptr vars below

void useDirect() { void (*fn)() = &alpha; fn(); }          // (a) address-of init → edge to alpha
void usePlain()  { H fnPtr = beta; fnPtr(); }              // (b) bare-name init, typedef'd type → edge to beta
void reassigned(){ void (*fn)() = &alpha; fn = &beta; fn(); }   // (c) double-assignment → TOMBSTONE, no edge
static H handlers[] = { &alpha, &beta };
void dispatch(int i) { handlers[i](); }                    // (d) dynamic table index → NO confident edge
void useLambda() { auto cb = [](){ helperFn(); }; cb(); }  // (e) lambda-bound → no false edge; helperFn stays
static H gPtr = &alpha;
void useFileScope() { gPtr(); }                            // (f) file-scope binding, never clobbered → alpha

// A5 escape-guard arms (adversarial-verifier refutation, 2026-08-09): a binding variable that ESCAPES —
// address taken, or bound to a reference — can be retargeted behind the resolver's back, so it clobbers.
void indirect_mutate( H* pfn ) { *pfn = &beta; }
void takes_fn( H p ) { p(); }
void escaped()  { void (*fn)() = &alpha; indirect_mutate(&fn); fn(); }  // (k) &fn escapes → NO edge at all
void byval()    { void (*fn)() = &alpha; takes_fn(fn); fn(); }          // (l) by-value copy → alpha SURVIVES
void refbound() { H fn2 = &alpha; H& r = fn2; fn2(); }                  // (m) reference-bound → NO edge
EOF

cat >"$FIX/valuenoise.cpp" <<'EOF'
// (n)-(q) value-assignment noise gate (r9 fix round): the assignment arm carries no type node, so before
// this gate ANY `x = y;` with a bare-identifier RHS minted an FnAssign — including a plain string copy. The
// corpus-wide assignByName sweep keys those records by VAR NAME ALONE, so one bogus record in this file
// TOMBSTONED the genuine, never-clobbered file-scope binding of the same name in fnptr.cpp.
#include <string>
typedef void (*H2)();
void alpha();
void beta();
std::string noiseCopy( std::string z ) { std::string gPtr; gPtr = z; return gPtr; }   // (n) must not clobber gPtr
int         noiseInt ( int z )         { int i = 0; i = z; return i; }                // (n) primitive-typed copy
void rebindRaw()   { void (*fq)(); fq = alpha; fq(); }        // (o) raw fn-ptr declarator rebind → alpha
void rebindAlias() { H2 fr = nullptr; fr = beta; fr(); }      // (p) typedef'd fn-ptr alias rebind → beta
EOF

cat >"$FIX/hdralias.h" <<'EOF'
// the fn-pointer type alias declared in ANOTHER file — the decl-arm gate's disclosed blind spot, pinned by
// (t) below so a future widening of the alias evidence has a green arm to flip and this one to delete.
typedef void (*HdrH)();
EOF

cat >"$FIX/valuedeclnoise.cpp" <<'EOF'
// (r)-(u) declaration-arm value-INITIALIZATION noise gate (r9 fix round): the decl arm gated a
// bare-identifier initializer on a PRIMITIVE written type only, so `std::string p = z;` minted an FnDecl.
// The recall side is what makes it a gate: an fn-pointer declarator, a same-file typedef alias, `auto`, and
// any template/dependent type all still mint — only a CONCRETE, non-alias written type is proven a value.
#include "hdralias.h"
#include <string>
#include <functional>
typedef void (*H3)();
struct Crate { int k; };
void alpha();
void beta();
void gamma();
std::string declNoiseStr( std::string z ) { std::string q = z; return q; }        // (r) class-typed init
Crate       declNoiseBox( Crate z )       { Crate q = z; return q; }              // (r) struct-typed init
void declKeepRaw()   { void (*q)() = alpha; q(); }               // (s) raw fn-ptr declarator → alpha
void declKeepAlias() { H3 q = beta; q(); }                       // (s) same-file alias       → beta
void declKeepAuto()  { auto q = gamma; q(); }                    // (s) auto is UNKNOWN       → gamma
void declKeepTmpl()  { std::function<void()> q = gamma; q(); }   // (s) template is UNKNOWN    → gamma
void declHdrAlias()  { HdrH q = beta; q(); }                     // (t) alias from a HEADER — see (t)
EOF

cat >"$FIX/cfile.c" <<'EOF'
/* fn-pointer binding gate fixture (C path) — generated by test/fnptrcheck.sh, never committed. */
typedef void (*FP)(void);
void gamma(void) {}
void cUse(void) { FP p = &gamma; p(); }
EOF

echo "fnptrcheck: BIN=$BIN  CORPUS=$FIX (generated)"

verb(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null; }
rows(){ verb "$1" | tr '>' '\n'; }   # one element per line so a row's own attributes can be grepped together

# ── (a) `void (*fn)() = &alpha; fn();` → edge useDirect → alpha, and NOT to the same-named global fn. ──
UD="$( rows --callees=useDirect )"
printf '%s\n' "$UD" | grep -q 'n="alpha"' \
    && ok "useDirect() has a callee row for alpha (address-of binding resolved)" \
    || no "useDirect() has NO callee row for alpha — the fn-pointer binding did not resolve"
printf '%s\n' "$UD" | grep -q 'n="fn"' \
    && no "useDirect() shows an edge to the GLOBAL fn — the bare-name ladder overrode the local binding" \
    || ok "useDirect() has no edge to the same-named global fn (binding dominates the name spray)"

# ── (b) `H fnPtr = beta; fnPtr();` (no address-of, typedef'd type) → edge usePlain → beta. ──
rows --callees=usePlain | grep -q 'n="beta"' \
    && ok "usePlain() has a callee row for beta (bare-identifier initializer resolved)" \
    || no "usePlain() has NO callee row for beta — the no-address-of binding did not resolve"

# ── (c) double-assignment tombstone: `fn = &alpha; ... fn = &beta; fn();` → NO edge to either (nor to global fn). ──
RA="$( rows --callees=reassigned )"
printf '%s\n' "$RA" | grep -q 'n="alpha"' \
    && no "reassigned() shows an edge to alpha — a double-assigned var must be tombstoned" \
    || ok "reassigned() has no alpha edge (tombstone held)"
printf '%s\n' "$RA" | grep -q 'n="beta"' \
    && no "reassigned() shows an edge to beta — a double-assigned var must be tombstoned" \
    || ok "reassigned() has no beta edge (tombstone held)"
printf '%s\n' "$RA" | grep -q 'n="fn"' \
    && no "reassigned() shows an edge to the GLOBAL fn — the tombstoned var must not fall back to the name ladder" \
    || ok "reassigned() has no edge to the same-named global fn (tombstone means NOTHING, not a guess)"

# ── (d) dynamic table dispatch: `handlers[i]()` → NO confident edge to any table member. ──
DI="$( rows --callees=dispatch )"
printf '%s\n' "$DI" | grep -q 'n="alpha"' \
    && no "dispatch() shows an edge to alpha — an indexed fn-pointer table must produce no confident edge" \
    || ok "dispatch() has no alpha edge (indexed table stays unresolved)"
printf '%s\n' "$DI" | grep -q 'n="beta"' \
    && no "dispatch() shows an edge to beta — an indexed fn-pointer table must produce no confident edge" \
    || ok "dispatch() has no beta edge (indexed table stays unresolved)"

# ── (e) lambda-bound: cb() produces no FALSE edge; helperFn stays attributed to the enclosing function. ──
UL="$( rows --callees=useLambda )"
printf '%s\n' "$UL" | grep -q 'n="helperFn"' \
    && ok "useLambda() keeps its helperFn edge (lambda body attribution unchanged)" \
    || no "useLambda() lost its helperFn edge — lambda-body attribution regression"
for bogus in alpha beta fn; do
    printf '%s\n' "$UL" | grep -q "n=\"$bogus\"" \
        && no "useLambda() grew a bogus $bogus edge — a lambda-bound var must resolve to nothing extra" \
        || ok "useLambda() has no $bogus edge (lambda binding produced no false edge)"
done

# ── (f) file-scope binding: `static H gPtr = &alpha;` never clobbered → useFileScope → alpha. ──
rows --callees=useFileScope | grep -q 'n="alpha"' \
    && ok "useFileScope() resolves gPtr() to alpha (file-scope binding, no clobber anywhere)" \
    || no "useFileScope() has NO alpha edge — the file-scope binding did not resolve"

# ── (g) the C path: `FP p = &gamma; p();` in a .c file → edge cUse → gamma. ──
rows --callees=cUse | grep -q 'n="gamma"' \
    && ok "cUse() (.c file) has a callee row for gamma (Lang::C binding capture live)" \
    || no "cUse() (.c file) has NO gamma edge — the C-grammar binding capture is missing"

# ── (k) ESCAPE clobber — `indirect_mutate(&fn)` can retarget fn through the pointer, so the binding is no
#        longer trustworthy: fn() resolves to NOTHING (not alpha, not beta, not the same-named global fn). ──
ES="$( rows --callees=escaped )"
for bogus in alpha beta fn; do
    printf '%s\n' "$ES" | grep -q "n=\"$bogus\"" \
        && no "escaped() shows an edge to $bogus — an address-taken binding var must be clobbered" \
        || ok "escaped() has no $bogus edge (address-of escape clobbers the binding)"
done
printf '%s\n' "$ES" | grep -q 'n="indirect_mutate"' \
    && ok "escaped() keeps its direct indirect_mutate call edge (the guard clobbers only the binding)" \
    || no "escaped() lost its indirect_mutate edge — the escape guard over-suppressed a direct call"

# ── (l) by-value control — `takes_fn(fn)` copies the pointer; a copy cannot mutate the variable, so the
#        binding stays live and fn() must STILL resolve to alpha (the guard must not over-suppress). ──
BV="$( rows --callees=byval )"
printf '%s\n' "$BV" | grep -q 'n="alpha"' \
    && ok "byval() still resolves fn() to alpha (a by-value use is not an escape)" \
    || no "byval() lost its alpha edge — the escape guard over-suppressed a by-value use"

# ── (m) reference-bind clobber — `H& r = fn2;` aliases the variable; a write through r is invisible, so
#        fn2() resolves to NOTHING. ──
RB="$( rows --callees=refbound )"
printf '%s\n' "$RB" | grep -q 'n="alpha"' \
    && no "refbound() shows an alpha edge — a reference-bound binding var must be clobbered" \
    || ok "refbound() has no alpha edge (reference binding clobbers)"

# ── (n) the value-assignment noise gate: a same-named string copy in ANOTHER file must not tombstone the
#        genuine, never-clobbered file-scope binding — `static H gPtr = &alpha;` still resolves. ──
rows --callees=useFileScope | grep -q 'n="alpha"' \
    && ok "useFileScope() keeps its alpha edge with a same-named \`std::string gPtr\` copy in another file" \
    || no "useFileScope() LOST its alpha edge — a value-typed \`gPtr = z;\` minted an FnAssign that tombstoned the file-scope binding"

# ── (o)-(p) the gate keeps GENUINE bare-identifier rebinds: a raw fn-pointer declarator and a typedef'd
#        fn-pointer alias are both proof the variable can hold a function. ──
rows --callees=rebindRaw | grep -q 'n="alpha"' \
    && ok "rebindRaw() resolves fq() to alpha (raw fn-pointer declarator licenses the bare-identifier rebind)" \
    || no "rebindRaw() has NO alpha edge — the noise gate ate a genuine raw fn-pointer rebind"
rows --callees=rebindAlias | grep -q 'n="beta"' \
    && ok "rebindAlias() resolves fr() to beta (a fn-pointer TYPE ALIAS licenses the bare-identifier rebind)" \
    || no "rebindAlias() has NO beta edge — the noise gate ate a genuine alias-typed fn-pointer rebind"

# ── (q) and it mints nothing for the copies themselves: noiseCopy/noiseInt gain no callee at all. ──
for fnq in noiseCopy noiseInt; do
    NC="$( rows --callees=$fnq )"
    printf '%s\n' "$NC" | grep -qE 'n="(alpha|beta|gamma)"' \
        && { no "$fnq() shows a bound-function edge — a value copy must mint no binding"; printf '%s\n' "$NC" | grep -E 'n="(alpha|beta|gamma)"'; } \
        || ok "$fnq() has no bound-function edge (a value copy is not a fn-pointer rebind)"
done

# ── (r) the DECLARATION arm's noise gate: a concrete, non-alias written type proves a value COPY, and a
#        copy mints no binding at all — declNoiseStr/declNoiseBox gain no bound-function callee. ──
for fnr in declNoiseStr declNoiseBox; do
    DN="$( rows --callees=$fnr )"
    printf '%s\n' "$DN" | grep -qE 'n="(alpha|beta|gamma)"' \
        && { no "$fnr() shows a bound-function edge — a value-typed initializer must mint no binding"; printf '%s\n' "$DN" | grep -E 'n="(alpha|beta|gamma)"'; } \
        || ok "$fnr() has no bound-function edge (a value-typed initializer is not a fn-pointer binding)"
done

# ── (s) and it keeps every FN-CAPABLE shape: a raw declarator, a same-file alias, `auto`, a template type.
#        `auto`/template are UNKNOWN written types and unknown MINTS — that is what keeps `auto fp = f;` alive. ──
rows --callees=declKeepRaw   | grep -q 'n="alpha"' \
    && ok "declKeepRaw() resolves q() to alpha (a raw fn-pointer declarator licenses a bare-identifier init)" \
    || no "declKeepRaw() has NO alpha edge — the decl-arm gate ate a raw fn-pointer binding"
rows --callees=declKeepAlias | grep -q 'n="beta"' \
    && ok "declKeepAlias() resolves q() to beta (a same-file fn-pointer TYPE ALIAS licenses it)" \
    || no "declKeepAlias() has NO beta edge — the decl-arm gate ate an alias-typed fn-pointer binding"
rows --callees=declKeepAuto  | grep -q 'n="gamma"' \
    && ok "declKeepAuto() resolves q() to gamma (\`auto\` is UNKNOWN and unknown mints)" \
    || no "declKeepAuto() has NO gamma edge — the decl-arm gate ate the idiomatic \`auto fp = f;\` binding"
rows --callees=declKeepTmpl  | grep -q 'n="gamma"' \
    && ok "declKeepTmpl() resolves q() to gamma (a template/dependent type is UNKNOWN and unknown mints)" \
    || no "declKeepTmpl() has NO gamma edge — the decl-arm gate ate a std::function-typed binding"

# ── (t) DISCLOSED BLIND SPOT: the fn-pointer alias evidence is SAME-FILE, so a typedef living in a header
#        leaves `HdrH q = beta;` looking exactly like a value copy and its edge is gated away. This arm pins
#        the disclosed behaviour, not a desired one — flip it to a positive when the alias evidence widens. ──
rows --callees=declHdrAlias | grep -q 'n="beta"' \
    && no "declHdrAlias() RESOLVED to beta — the alias evidence widened past same-file; flip this arm to a positive and update the decl-arm gate comment + the --uses/legend disclosure" \
    || ok "declHdrAlias() has no beta edge (DISCLOSED: a fn-pointer typedef declared in a header is invisible to the per-file alias evidence)"

# ── (h) edge honesty: the resolved rows are plain calls — no role= relabel (a binding is not a macro). ──
printf '%s\n' "$UD" | grep 'n="alpha"' | grep -q 'role=' \
    && no "useDirect's alpha row carries a role= attribute — a binding-resolved call must stay a plain call row" \
    || ok "useDirect's alpha row is a plain call row (no role= relabel)"

# ── (i) determinism — binding edges must be byte-stable run-to-run. ──
"$BIN" "$FIX" --no-cache >"$TMP/m1" 2>/dev/null
"$BIN" "$FIX" --no-cache >"$TMP/m2" 2>/dev/null
diff -q "$TMP/m1" "$TMP/m2" >/dev/null && ok "deterministic (fnptrfix map byte-identical across two runs)" \
    || { no "non-deterministic fnptrfix map"; diff "$TMP/m1" "$TMP/m2" | head -6; }

# ── (j) cache transparency — fn-binding facts round-trip the incremental cache: warm == cold. ──
rm -f "$TMP/cc"
"$BIN" "$FIX" --cache="$TMP/cc" >/dev/null 2>&1
"$BIN" "$FIX" --cache="$TMP/cc" >"$TMP/warm" 2>/dev/null
"$BIN" "$FIX" --no-cache        >"$TMP/cold" 2>/dev/null
diff -q "$TMP/warm" "$TMP/cold" >/dev/null && ok "cache-transparent (fn-binding facts round-trip: warm == cold)" \
    || { no "cache changes output (warm != cold)"; diff "$TMP/cold" "$TMP/warm" | head -6; }

[ "$fail" = 0 ] && echo "ALL PASS" || echo "FAILURES ABOVE"
exit $fail
