#!/usr/bin/env bash
# genrecallcheck.sh — gate for the GENERATED-DOCUMENT de-prioritization in the --recall lens
# (PLAN_outputAudit_2026-07-28.md §P2b). A generated artifact — a command capture, an API dump, a doxygen
# export — QUOTES the whole system it documents, so BM25 hands it every query's terms and it out-scores the
# design doc that EXPLAINS them. This repo solved its own case by relocating docs/captures/ under a
# crawl-skipped name; every OTHER repo with large generated documentation still hit it, because the tool had
# no notion that a generated artifact is not a design document. It has one now (src/docparse.h:
# classifyGeneratedDoc), and --recall ranks such a document LAST — a heavy penalty, never a filter.
#
# The corpus below is synthetic on purpose: five hand-written design docs (~2–3 KB each), one 100 KB+
# capture that is mostly ``` -fenced quoted output and repeats the query's terms in every block, and one
# API dump that DECLARES itself generated in its header. Both generated docs lexically dominate a query
# they cannot actually answer.
#
# RED (binary at HEAD~, before the §P2b change) — measured, not assumed:
#   #1 doc for "cache eviction policy ttl expiry"      = capture_generated.md   (design_cachepolicy.md #2)
#   #1 doc for "widget config schema field validation" = apidump_marker.md      (design_widget.md #2)
#   nothing in the output discloses either as generated.
# GREEN (this gate): the hand-written design doc wins BOTH, each generated doc is disclosed with the
#   evidence that demoted it, a hand-written doc is never demoted, and a query only the capture can answer
#   still returns the capture at #1.
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/genrecallcheck.sh   |   RIPWIRE_BIN=asan/ripwire bash …
# Exits non-zero on any failure. Does NOT edit regression.sh.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first"; exit 2; }
echo "genrecallcheck: BIN=$BIN"

TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
R="$TMP/repo"; mkdir -p "$R"

# ── the corpus ───────────────────────────────────────────────────────────────────────────────────────
# 1) the hand-written design docs. Each states its topic once, the way a real design doc does — it EXPLAINS
#    rather than quotes, so it can never win a term-count contest against a capture of the same subject.
{
  echo '# Cache eviction policy'
  echo
  echo 'Why the cache evicts what it evicts: capacity pressure, the ttl expiry sweep, and the'
  echo 'policy that decides which entry loses. The eviction policy is LRU with a ttl floor.'
  echo
  i=0; while [ $i -lt 40 ]; do
    echo "Rationale paragraph $i — the eviction decision is taken by the policy owner, not the caller."
    i=$(( i + 1 ))
  done
} >"$R/design_cachepolicy.md"
{
  echo '# Widget configuration design'
  echo
  echo 'How a widget config is declared, which schema validates it, and what a field means.'
  echo 'The config schema is the contract; validation is the gate that enforces it.'
  echo
  i=0; while [ $i -lt 40 ]; do
    echo "Rationale paragraph $i — a widget config change is a contract change for every consumer."
    i=$(( i + 1 ))
  done
} >"$R/design_widget.md"
for topic in scheduler transport telemetry; do
  {
    echo "# $topic design"
    echo
    i=0; while [ $i -lt 40 ]; do
      echo "The $topic subsystem, paragraph $i — its invariants, its owners, and why it is shaped this way."
      i=$(( i + 1 ))
    done
  } >"$R/design_$topic.md"
done

# 2) the capture: no marker at all, but 100 KB+ (>> 5x the corpus median) and mostly fenced quoted output —
#    caught by EVIDENCE alone (size + fence density), which is the arm that generalizes to any repo. It
#    also carries one token that exists nowhere else (zzcaptureonlytoken), for the never-dropped check.
{
  echo '# every command, run for real'
  echo
  echo 'Output of each command, captured verbatim on 2026-07-28.'
  echo
  i=0; while [ $i -lt 700 ]; do
    echo '```'
    echo "\$ tool --cache eviction policy ttl expiry --widget config schema field validation"
    echo "cache eviction policy ttl expiry: ok (row $i)"
    echo "widget config schema field validation: ok (row $i)"
    echo "zzcaptureonlytoken row $i"
    echo '```'
    i=$(( i + 1 ))
  done
} >"$R/capture_generated.md"

# 3) the API dump: it SAYS it is generated, in its first lines. Prose-shaped and far below the size line —
#    only the marker arm can catch it, which is exactly what the reason tag must report.
{
  echo '# Widget API reference'
  echo '<!-- @generated by apidump 3.2 — DO NOT EDIT -->'
  echo
  i=0; while [ $i -lt 120 ]; do
    echo "widget config schema field validation — entry $i: config field schema validation widget."
    i=$(( i + 1 ))
  done
} >"$R/apidump_marker.md"

run(){ perl -e 'alarm 30; exec @ARGV' "$BIN" "$R" --recall="$1" --no-cache 2>/dev/null; }
top_doc(){ printf '%s' "$1" | grep -F '━━' | head -1 | grep -oE '/[^ ]*\.md' | sed 's#.*/##'; }
hdr(){ local whole="$1"; printf '%s' "${whole%%$'\n'*}"; }   # first line, without a pipe (no SIGPIPE noise)
tally(){ hdr "$1" | grep -oE 'generated_demoted=[0-9]+'; }
# the demotion note emitted on ONE doc's separator line, or "" when that doc carries none
note_for(){ printf '%s' "$1" | grep -F '━━' | grep -F "/$2 " | grep -oE '\[generated_demoted: [a-z+]+\]'; }

CACHE="$( run "cache eviction policy ttl expiry" )"
WIDGET="$( run "widget config schema field validation" )"

# ── 1) the size+fences arm: the design doc beats the capture that quotes it ──────────────────────────
[ "$( top_doc "$CACHE" )" = "design_cachepolicy.md" ] \
    && ok "size+fences arm: design_cachepolicy.md ranked #1 over the 100KB capture (RED: capture was #1)" \
    || no "size+fences arm: top doc is '$( top_doc "$CACHE" )', expected design_cachepolicy.md"

# ── 2) the marker arm: a self-declared generated dump loses to the design doc ────────────────────────
[ "$( top_doc "$WIDGET" )" = "design_widget.md" ] \
    && ok "marker arm: design_widget.md ranked #1 over the @generated API dump (RED: dump was #1)" \
    || no "marker arm: top doc is '$( top_doc "$WIDGET" )', expected design_widget.md"

# ── 3) the demotion is DISCLOSED, per doc, with the evidence that caused it ──────────────────────────
[ "$( note_for "$CACHE" capture_generated.md )" = "[generated_demoted: size+fences]" ] \
    && ok "capture_generated.md discloses [generated_demoted: size+fences] on its own line" \
    || no "capture_generated.md carries no size+fences demotion note (got '$( note_for "$CACHE" capture_generated.md )')"
[ "$( note_for "$WIDGET" apidump_marker.md )" = "[generated_demoted: marker]" ] \
    && ok "apidump_marker.md discloses [generated_demoted: marker] on its own line" \
    || no "apidump_marker.md carries no marker demotion note (got '$( note_for "$WIDGET" apidump_marker.md )')"

# ── 4) the header tallies it — a reader who never scrolls still learns the ranking was reshaped. The
#      tally counts the generated docs the QUERY matched: the capture alone for the cache query, both the
#      capture and the API dump for the widget query (a tally of everything indexed would be noise).
[ "$( tally "$CACHE" )" = "generated_demoted=1" ] \
    && ok "header tallies generated_demoted=1 for the cache query (the capture)" \
    || no "cache query tally is '$( tally "$CACHE" )', expected generated_demoted=1: $( hdr "$CACHE" )"
[ "$( tally "$WIDGET" )" = "generated_demoted=2" ] \
    && ok "header tallies generated_demoted=2 for the widget query (capture + API dump)" \
    || no "widget query tally is '$( tally "$WIDGET" )', expected generated_demoted=2: $( hdr "$WIDGET" )"

# ── 5) hand-written docs are NEVER demoted (the false-positive direction is the expensive one) ───────
{ [ -z "$( note_for "$CACHE" design_cachepolicy.md )" ] && [ -z "$( note_for "$WIDGET" design_widget.md )" ] \
  && [ -z "$( note_for "$WIDGET" design_scheduler.md )" ]; } \
    && ok "no hand-written doc demoted — the design docs carry no demotion note" \
    || no "a hand-written doc was demoted (design_cachepolicy / design_widget / design_scheduler)"

# ── 6) de-prioritized, NOT dropped: a question only the capture can answer still returns the capture ──
ONLY="$( run "zzcaptureonlytoken" )"
{ [ "$( top_doc "$ONLY" )" = "capture_generated.md" ] \
  && [ -n "$( note_for "$ONLY" capture_generated.md )" ]; } \
    && ok "capture still ranked #1 (and still disclosed) when nothing else matches — demoted, not dropped" \
    || no "capture not returned for a capture-only query: top='$( top_doc "$ONLY" )'"

# ── 7) determinism — the classification reads files, so prove it adds no order dependence ────────────
[ "$( run "cache eviction policy ttl expiry" )" = "$CACHE" ] \
    && ok "--recall with demotion is deterministic (byte-identical run-to-run)" \
    || no "--recall with demotion is non-deterministic"

[ "$fail" = 0 ] && echo "ALL PASS" || echo "FAILURES ABOVE"
exit $fail
