#!/usr/bin/env bash
# macroedgecheck.sh — gate for the macro-edges round (function-like #define becomes a call-graph participant).
#
# The disclosed gap this closes: every graph-count legend said "a macro-generated call site ... contributes
# no edge". Post-round, a FUNCTION-LIKE `#define NAME(args) body` with a non-empty body is an indexed,
# disclosed-degraded symbol (t="macro"), the call-shaped invocation of its name carries role="macro" — NEVER
# role="call" (call-edge honesty: an expansion is not a plain call) — and the calls inside its replacement
# text produce edges FROM the macro symbol, so the graph connects through it (handler -> LOG_ERR -> logImpl).
# Object-like `#define MAXN 42` stays a non-participant on the C++ path (not even a symbol), and an
# empty-body function-like macro defines nothing callable, so it stays unindexed too.
#
# The fixture is GENERATED here (self-contained; nothing committed under test/):
#   log.h   — a MACRO-ONLY header (the ensemble.h coverage hole: pre-round it contributed ZERO symbols):
#             LOG_ERR (body calls logImpl), RETRY (body calls tryOnce through do/while+if — keyword +
#             macro-param filtering exercised), MAXN (object-like control), NOOP (empty-body control).
#   app.cpp — logImpl/tryOnce real defs; handler() invokes LOG_ERR; loopIt() invokes RETRY(tryOnce())
#             (the macro-ARGUMENT call parses as a normal call and must SURVIVE) and reads MAXN.
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/macroedgecheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/macrofix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/log.h" <<'EOF'
// macro-edges gate fixture — generated by test/macroedgecheck.sh, never committed.
// This header holds ONLY preprocessor definitions: pre-round it was symbol-empty.
#define LOG_ERR(msg) logImpl(msg, __FILE__)
#define RETRY(x) do { if( !(x) ) tryOnce(); } while(0)
#define MAXN 42
#define NOOP(x)
EOF

cat >"$FIX/app.cpp" <<'EOF'
// macro-edges gate fixture — generated by test/macroedgecheck.sh, never committed.
#include "log.h"
int logImpl(const char* m, const char* f) { return (m && f) ? 1 : 0; }
int tryOnce() { return 2; }
int handler() { LOG_ERR("boom"); return 0; }
int loopIt() { RETRY(tryOnce()); return MAXN + 1; }
EOF

echo "macroedgecheck: BIN=$BIN  CORPUS=$FIX (generated)"

verb(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null; }
rows(){ verb "$1" | tr '>' '\n'; }   # one element per line so a row's own attributes can be grepped together

# ── 1) the macro edge, tagged honestly: --callees=handler emits the LOG_ERR row as t="macro" role="macro". ──
HC="$( rows --callees=handler )"
if printf '%s\n' "$HC" | grep -q 'n="LOG_ERR"'; then
    ok "handler() has a callee row for LOG_ERR (the macro invocation is an edge)"
else
    no "handler() has NO callee row for LOG_ERR — the macro invocation still contributes no edge"
fi
LR="$( printf '%s\n' "$HC" | grep 'n="LOG_ERR"' | head -1 )"
printf '%s' "$LR" | grep -q 't="macro"' \
    && ok "the LOG_ERR row carries t=\"macro\" (disclosed macro kind)" \
    || no "the LOG_ERR row is not t=\"macro\": ${LR:-<no row>}"
printf '%s' "$LR" | grep -q 'role="macro"' \
    && ok "the LOG_ERR row carries role=\"macro\" (edge crosses an expansion)" \
    || no "the LOG_ERR row has no role=\"macro\": ${LR:-<no row>}"
printf '%s\n' "$HC" | grep -q 'role="call"' \
    && no "--callees=handler emits a role=\"call\" row — macro edges must NEVER be labelled plain calls" \
    || ok "--callees=handler emits no role=\"call\" anywhere (call-edge honesty)"

# ── 2) the graph CONNECTS through the macro: LOG_ERR -> logImpl (body call), both directions visible. ──
rows --callees=LOG_ERR | grep -q 'n="logImpl"' \
    && ok "LOG_ERR (macro symbol) has a callee edge to logImpl (replacement-text call captured)" \
    || no "LOG_ERR has no callee edge to logImpl — the macro body's call was not captured"
rows --callers=logImpl | grep -q 'n="LOG_ERR"' \
    && ok "logImpl's callers include LOG_ERR (the macro symbol, not a dead end)" \
    || no "logImpl's callers do NOT include LOG_ERR"

# ── 3) --uses=LOG_ERR: the macro now HAS a definition (defs>=1, external gone) and the invocation site
#       carries role="macro", never role="call". ──
UU="$( verb --uses=LOG_ERR )"
printf '%s' "$UU" | grep -q 'defs="1"' \
    && ok "--uses=LOG_ERR reports defs=\"1\" (the #define is an indexed definition)" \
    || no "--uses=LOG_ERR does not report defs=\"1\": $( printf '%s' "$UU" | grep -o '<uses [^>]*' | head -1 )"
printf '%s' "$UU" | grep -q 'external="0"' \
    && ok "--uses=LOG_ERR reports external=\"0\" (no longer a phantom external)" \
    || no "--uses=LOG_ERR still claims external: $( printf '%s' "$UU" | grep -o 'external="[01]"' | head -1 )"
printf '%s' "$UU" | grep -q '<u role="macro"' \
    && ok "the invocation site carries role=\"macro\"" \
    || no "no role=\"macro\" use-site for LOG_ERR"
printf '%s' "$UU" | grep -q '<u role="call"' \
    && no "--uses=LOG_ERR still shows a role=\"call\" site — the honesty retag missed it" \
    || ok "--uses=LOG_ERR shows no role=\"call\" site"

# ── 4) macro-argument call survives + RETRY edge appears: loopIt -> tryOnce AND loopIt -> RETRY. ──
LC="$( rows --callees=loopIt )"
printf '%s\n' "$LC" | grep -q 'n="tryOnce"' \
    && ok "loopIt() keeps its edge to tryOnce (the macro-ARGUMENT call parses as a normal call)" \
    || no "loopIt() lost its tryOnce edge — macro-argument call regression"
printf '%s\n' "$LC" | grep 'n="RETRY"' | grep -q 'role="macro"' \
    && ok "loopIt() gains the RETRY edge, tagged role=\"macro\"" \
    || no "loopIt() has no role=\"macro\" RETRY row"

# ── 5) object-like + empty-body controls: MAXN and NOOP are NOT call-edge participants (C++ path). ──
printf '%s\n' "$LC" | grep -q 'n="MAXN"' \
    && no "loopIt() grew a MAXN edge — an object-like #define must not be a call-edge participant" \
    || ok "no MAXN edge from loopIt() (object-like #define stays out of the call graph)"
MAP="$TMP/map.xml"
"$BIN" "$FIX" --no-cache --top-k=100000 >"$MAP" 2>/dev/null
grep -q 'n="MAXN"' "$MAP" \
    && no "MAXN (object-like) was indexed as a symbol on the C++ path" \
    || ok "MAXN (object-like) is not indexed on the C++ path"
grep -q 'n="NOOP"' "$MAP" \
    && no "NOOP (empty-body function-like) was indexed — an empty body defines nothing callable" \
    || ok "NOOP (empty-body function-like) stays unindexed"

# ── 6) the macro-only header contributes symbols (the ensemble.h coverage hole). ──
if grep -oE '<s [^>]*' "$MAP" | grep 'log\.h' | grep -q 'n="LOG_ERR"'; then
    ok "log.h (macro-only header) contributes the LOG_ERR symbol to the map"
else
    # p= layout differs between map shapes — fall back to: the symbol row exists with t="macro".
    grep -oE '<s [^>]*n="LOG_ERR"[^>]*' "$MAP" | grep -q 't="macro"' \
        && ok "LOG_ERR is an indexed t=\"macro\" symbol (macro-only header no longer empty)" \
        || no "log.h contributed no LOG_ERR symbol — the macro-only-header hole is still open"
fi

# ── 7) determinism — macro symbols/edges must be byte-stable run-to-run. ──
"$BIN" "$FIX" --no-cache >"$TMP/m1" 2>/dev/null
"$BIN" "$FIX" --no-cache >"$TMP/m2" 2>/dev/null
diff -q "$TMP/m1" "$TMP/m2" >/dev/null && ok "deterministic (macrofix map byte-identical across two runs)" \
    || { no "non-deterministic macrofix map"; diff "$TMP/m1" "$TMP/m2" | head -6; }

# ── 8) cache transparency — macro facts round-trip the incremental cache: warm == cold. ──
rm -f "$TMP/cc"
"$BIN" "$FIX" --cache="$TMP/cc" >/dev/null 2>&1
"$BIN" "$FIX" --cache="$TMP/cc" >"$TMP/warm" 2>/dev/null
"$BIN" "$FIX" --no-cache        >"$TMP/cold" 2>/dev/null
diff -q "$TMP/warm" "$TMP/cold" >/dev/null && ok "cache-transparent (macro facts round-trip: warm == cold)" \
    || { no "cache changes output (warm != cold)"; diff "$TMP/cold" "$TMP/warm" | head -6; }

[ "$fail" = 0 ] && echo "ALL PASS" || echo "FAILURES ABOVE"
exit $fail
