#!/usr/bin/env bash
# rtacheck.sh — gate for B2.1b RTA-lite (Bacon/Sweeney refinement of the CHA-lite cone, graph.h::buildGraph).
# The cone of a still-ambiguous receiver-typed call is intersected with the corpus's INSTANTIATED set — class
# names holding constructor evidence in the reference stream (`T()` call refs naming a class-like def;
# `new T(…)` in JS/TS/Java/C# via their object-creation @reference.call tags patterns; value-member compose
# "creates" refs). Non-empty intersection narrows the tier; EMPTY intersection DEGRADES to the plain cone —
# the filter may only ever REMOVE candidates when evidence supports it, never empty a tier, never drop a call
# edge CHA-lite kept (shrink-never-drop).
#
# The fixture is GENERATED here (self-contained; nothing committed under test/):
#   rta.cpp — Shape (PURE-virtual draw — no base def, so Rule 2's canonical Shape::draw lookup misses and
#             the call reaches the ambiguous name tier) + Circle/Square/Triangle overriders. makeCircle()
#             holds the ONLY constructor evidence (`return Circle();` — a call_expression ref). renderOne()
#             calls s->draw() through a BOUND local (`Shape* s = getShape();`) → cone = whole hierarchy,
#             all three overriders survive it → RTA narrows to Circle::draw ALONE.
#             Widget (pure-virtual poke) + Btn/Box overriders, factoryDecl() DECLARED only — nothing in
#             the corpus constructs any of them → pokeIt()'s w->poke() intersection is EMPTY → degrade →
#             both poke defs survive, amb= honesty preserved.
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/rtacheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/rtafix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/rta.cpp" <<'EOF'
// RTA-lite gate fixture — generated by test/rtacheck.sh, never committed.
struct Shape { virtual int draw() = 0; };
struct Circle : Shape { int draw() override { return 1; } };
struct Square : Shape { int draw() override { return 2; } };
struct Triangle : Shape { int draw() override { return 3; } };
Shape* getShape();
Circle makeCircle() { return Circle(); }
int renderOne() { Shape* s = getShape(); return s->draw(); }

struct Widget { virtual int poke() = 0; };
struct Btn : Widget { int poke() override { return 10; } };
struct Box : Widget { int poke() override { return 20; } };
Widget* factoryDecl();
int pokeIt() { Widget* w = factoryDecl(); return w->poke(); }
EOF

echo "rtacheck: BIN=$BIN  CORPUS=$FIX (generated)"

# derive the def line numbers from the generated source so the gate survives fixture edits.
CIRCLE_LINE="$(   grep -n 'struct Circle'   "$FIX/rta.cpp" | cut -d: -f1 )"   # Circle::draw (in-class body)
SQUARE_LINE="$(   grep -n 'struct Square'   "$FIX/rta.cpp" | cut -d: -f1 )"   # Square::draw
TRIANGLE_LINE="$( grep -n 'struct Triangle' "$FIX/rta.cpp" | cut -d: -f1 )"   # Triangle::draw
BTN_LINE="$(      grep -n 'struct Btn'      "$FIX/rta.cpp" | cut -d: -f1 )"   # Btn::poke
BOX_LINE="$(      grep -n 'struct Box'      "$FIX/rta.cpp" | cut -d: -f1 )"   # Box::poke

# distinct target def lines a caller resolves to (via --callees), rta.cpp only.
targets(){ "$BIN" "$FIX" --callees="$1" --no-cache 2>/dev/null | tr '>' '\n' | grep -oE 'rta\.cpp:[0-9]+' | grep -oE '[0-9]+$' | sort -un; }

# ── 1) RTA positive: renderOne()'s s->draw() narrows to Circle::draw ALONE — Circle is the only class with
#       constructor evidence, so Shape/Square/Triangle defs are pruned from the cone. ──
rT="$( targets renderOne )"                       # also holds getShape — only the draw defs are judged
drawT="$( printf '%s\n' "$rT" | grep -Ex "$CIRCLE_LINE|$SQUARE_LINE|$TRIANGLE_LINE" )"
drawN="$( printf '%s\n' "$drawT" | grep -c . )"
if [ "$drawN" = "1" ] && printf '%s\n' "$drawT" | grep -qx "$CIRCLE_LINE"; then
    ok "RTA positive: renderOne() → Circle::draw ONLY (Square/Triangle pruned, $drawN draw target)"
else
    no "RTA positive: renderOne() draw targets = [$(echo $drawT)] (want ONLY line $CIRCLE_LINE=Circle; NOT $SQUARE_LINE/$TRIANGLE_LINE)"
fi

# ── 2) RTA degrade: pokeIt()'s hierarchy holds NO constructor evidence (factory DECLARED only) → the
#       intersection is empty → the plain cone survives untouched: BOTH poke defs stay candidates. ──
pT="$( targets pokeIt )"
pokeT="$( printf '%s\n' "$pT" | grep -Ex "$BTN_LINE|$BOX_LINE" )"
pokeN="$( printf '%s\n' "$pokeT" | grep -c . )"
if [ "$pokeN" = "2" ] && printf '%s\n' "$pokeT" | grep -qx "$BTN_LINE" && printf '%s\n' "$pokeT" | grep -qx "$BOX_LINE"; then
    ok "RTA degrade: pokeIt() keeps BOTH Btn/Box poke (empty intersection → plain cone, $pokeN targets)"
else
    no "RTA degrade: pokeIt() poke targets = [$(echo $pokeT)] (want BOTH $BTN_LINE + $BOX_LINE — an unconstructed hierarchy must NOT be narrowed)"
fi

# ── 3) amb honesty: renderOne is resolved (no amb marker), pokeIt stays flagged (amb=). ──
MAP="$TMP/map.xml"
"$BIN" "$FIX" --no-cache --top-k=100000 >"$MAP" 2>/dev/null
if grep -oE 'n="renderOne"[^>]*' "$MAP" | grep -q 'amb='; then
    no "renderOne() still carries amb= (RTA-lite did not resolve it)"; else ok "renderOne() carries NO amb= (resolved by RTA-lite)"; fi
if grep -oE 'n="pokeIt"[^>]*' "$MAP" | grep -q 'amb='; then
    ok "pokeIt() carries amb= (honest ambiguity preserved on the evidence-free control)"
else no "pokeIt() lost its amb= (the degrade control should stay ambiguous)"; fi

# ── 4) determinism — the instantiated-set build + intersection must be byte-stable run-to-run. ──
"$BIN" "$FIX" --no-cache >"$TMP/m1" 2>/dev/null
"$BIN" "$FIX" --no-cache >"$TMP/m2" 2>/dev/null
diff -q "$TMP/m1" "$TMP/m2" >/dev/null && ok "deterministic (rtafix map byte-identical across two runs)" \
    || { no "non-deterministic rtafix map"; diff "$TMP/m1" "$TMP/m2" | head -6; }

# ── 5) cache transparency — the RTA narrowing survives the incremental cache: warm == cold. ──
rm -f "$TMP/cc"
"$BIN" "$FIX" --cache="$TMP/cc" >/dev/null 2>&1
"$BIN" "$FIX" --cache="$TMP/cc" >"$TMP/warm" 2>/dev/null
"$BIN" "$FIX" --no-cache        >"$TMP/cold" 2>/dev/null
diff -q "$TMP/warm" "$TMP/cold" >/dev/null && ok "cache-transparent (RTA facts round-trip: warm == cold)" \
    || { no "cache changes output (warm != cold)"; diff "$TMP/cold" "$TMP/warm" | head -6; }

[ "$fail" = 0 ] && echo "ALL PASS" || echo "FAILURES ABOVE"
exit $fail
