#!/usr/bin/env bash
# shadowcheck.sh — gate for local-shadow suppression (r9 loss bucket 2, kParserVer 52).
#
# The measured failure: a local variable that SHADOWS a function's name got its read/write/mention sites
# falsely attributed to the function — `int run = 0;` inside worker() put worker's `run` arithmetic into
# --uses=run (13 false sites on one r9 query). Post-round, a reference site to name N inside a function
# whose LOCAL DECLARATIONS bind N as a variable is NOT attributed to any indexed symbol named N (the local
# wins for the whole scope — C++ name lookup). Guards this gate pins alongside the suppression itself:
#   * ZERO recall loss on genuine calls: a real run() call in another function — and in the SAME function
#     as an unrelated shadow — must survive;
#   * the L3 fn-pointer discipline is untouched: `void (*cb)() = &run; cb();` still resolves its edge (a
#     fn-binding var's references are calls THROUGH the variable, never suppressed);
#   * the no-collision feature survives: --uses on a plain local name with NO same-named indexed symbol
#     (writetargetcheck's whole contract) still lists its sites — suppression needs a collision;
#   * iteration 4 — an ordinary block declaration shadows from its DECLARATION POINT (the end of its
#     complete declarator, C++ [basic.scope.pdecl]), NOT from the block's opening brace, so a genuine call
#     written ABOVE the shadowing local survives; the shapes whose names are in scope from the start of
#     their scope (definition/lambda/catch parameters, captures, range-for variables, control-statement
#     header declarations) keep their whole-body/whole-statement spans and must not regain false positives.
#
# The fixture is GENERATED here (self-contained; nothing committed under test/).
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/shadowcheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/shadowfix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/funcs.h" <<'EOF'
// shadow gate fixture — generated by test/shadowcheck.sh, never committed.
void run();
void process(int v);
EOF

cat >"$FIX/funcs.cpp" <<'EOF'
#include "funcs.h"
void run() {}
void process(int v) { (void)v; }
EOF

cat >"$FIX/shadowed.cpp" <<'EOF'
#include "funcs.h"
int use(int x) { return x; }
void worker() {
    int run = 0;      // the LOCAL shadows function run() for this whole scope
    run += 1;
    int y = run + 2;
    use(run);
    use(y);
}
EOF

cat >"$FIX/caller.cpp" <<'EOF'
#include "funcs.h"
void boss() {
    run();            // a GENUINE call — zero recall loss is the bar
}
EOF

cat >"$FIX/mixed.cpp" <<'EOF'
#include "funcs.h"
void tricky() {
    int process = 0;  // shadows process() ...
    process += 3;     // ... so these sites are the local's
    run();            // ... while THIS genuine call must survive in the same scope
    (void)process;
}
EOF

cat >"$FIX/fnptr.cpp" <<'EOF'
#include "funcs.h"
void useCb() {
    void (*cb)() = &run;   // an L3 fn-binding var — cb's references are calls THROUGH the variable
    cb();                  // must still resolve to run() (never shadow-suppressed)
}
EOF

cat >"$FIX/refshapes.cpp" <<'EOF'
// A5 fix-round arms: reference declarators, structured bindings, inner-block spans, lambdas.
struct Pr { int key; int w; };
void key();            // the shadowed function (defined in funcs2.cpp)
void keyCaller() { key(); }                                        // genuine call — recall anchor
int  refParam(const int& key) { int x = key; return x; }           // (f) pass-by-const-ref param shadow
void refLocal() { int g0 = 0; int& key = g0; (void)key; }          // (g) reference-typed local shadow
void sbRange() { Pr ps[2] = {}; for (const auto& [key, w] : ps) { (void)key; (void)w; } }  // (h)
void lamParam() { auto f = [](int key) { return key + 1; }; (void)f; }        // (j) lambda param shadow
void lamInit()  { auto g = [key = 3]() { return key; }; (void)g; }            // (k) init-capture shadow
void lamCap()   { int key = 1; auto h = [key]() { return key; }; (void)h; }   // (l) simple capture of a shadowing local
EOF

cat >"$FIX/funcs2.cpp" <<'EOF'
void key() {}
EOF

cat >"$FIX/innerblock.cpp" <<'EOF'
#include "funcs.h"
void innerBlock() {
    {
        int run = 0;   // shadows run() INSIDE THIS BLOCK only
        run += 1;
    }
    run();             // (i) a GENUINE call after the block closes — block-span suppression must keep it
}
EOF

cat >"$FIX/ctrlinit.cpp" <<'EOF'
// A5 iteration-3 arms: control-statement HEADER declarations scope to the STATEMENT, not the enclosing block.
#include "funcs.h"
int  getVal();
void forInit() {
    for (int run = 0; run < 3; ++run) { (void)run; }   // header decl + body use — all suppressed
    run();                                             // (m) TWO genuine calls after the loop — both survive
    run();
}
void ifInit() {
    if (int run = getVal()) { (void)run; }             // (n) if-init variant
    run();
}
void whileCond() {
    while (int run = getVal()) { (void)run; }          // (o) while-condition variant
    run();
}
EOF

cat >"$FIX/catchparam.cpp" <<'EOF'
#include "funcs.h"
struct Error { };
void catcher() {
    try { throw Error(); }
    catch (const Error& process) {                     // (p) catch param shadows process()
        (void)process;
    }
    run();
}
EOF

cat >"$FIX/predecl.cpp" <<'EOF'
// A5 iteration-4 arms: an ordinary block declaration shadows from its DECLARATION POINT — the end of the
// complete declarator (C++ [basic.scope.pdecl]) — never from the enclosing block's opening brace.
#include "funcs.h"
struct Pr2 { int one; int two; };
int  probe() { return 0; }
void slot()  { }
Pr2  mkPr2() { return Pr2{}; }
void preDecl() {
    run();                                   // (q) a GENUINE call written BEFORE the local exists — survives
    int run = 0;                             // ... the declaration point ...
    run += 1;                                // ... and the LOCAL's own sites, which stay suppressed
    (void)run;
}
void multiDecl() {
    int a = probe(), probe = 0, b = probe;   // (r) the call in a's initializer is BEFORE probe's declarator;
    (void)a; (void)b; (void)probe;           //     b's read is AFTER it, so it is the local's
}
void selfInit() {
    int probe = probe;                       // (s) [basic.scope.pdecl]: the initializer's probe IS the local
    (void)probe;
}
void sbDecl() {
    slot();                                  // (u) genuine call before a structured-binding declaration,
    auto [slot, w] = mkPr2();                //     whose locus is after the identifier-list
    (void)slot; (void)w;
}
// (q4)/(q5) a BARE declarator's own name is not a read of the function it shadows — nor is the SECOND
// declarator's, since one `declaration` node carries one `declarator` FIELD per declared name.
void bareDecl()  { int run; run = 0; (void)run; }
void bareDecl2() { int one, run; (void)one; (void)run; }
// (q6)/(q7)/(q8) the declarator shapes arm 2's `declarator`-FIELD probe cannot reach are declarations all
// the same. A DEFAULTED parameter hangs its name off `optional_parameter_declaration` — the sibling of the
// `parameter_declaration` arm 2 does list — while a pack (`variadic_declarator`) and an attributed
// declarator (`attributed_declarator`) name the child by no field at all, so the probe returns null.
void optParam(int run = 0) { (void)run; }
template<typename... Ts> void packParam(Ts... run) { }
// attrDecl carries NO body use on purpose: `attributed_declarator` is a shape emitShadowVarDecls does not
// unwrap, so it records no shadow BINDING and a body read would stay name-matched — the under-suppression
// floor that capture already discloses. This arm pins the DECLARED name, which is never a use either way.
void attrDecl() { int run [[maybe_unused]]; }
// (q9) GUARD: only the DECLARATOR field is a declaration site. A parameter's DEFAULT VALUE is an ordinary
// expression living in a different field, so a call written there stays a genuine call site.
void defaultCall(int v = probe()) { (void)v; }
EOF

cat >"$FIX/scopeguards.cpp" <<'EOF'
// A5 iteration-4 guards: the shapes whose names are in scope from the START of their scope KEEP their
// whole-body/whole-statement spans — narrowing THESE to a declaration point re-mints the false positives
// iterations 1-3 removed.
#include "funcs.h"
struct Err2 { };
int arr3[3] = { 1, 2, 3 };
void emit(int v) { (void)v; }
int  paramFirst(int run) { int x = run; return x; }   // (v) a param covers the FIRST body statement
void rangeForPre() {
    run();                                            // (w) genuine call BEFORE the loop ...
    for (int run : arr3) { (void)run; }               //     the loop var scopes to the WHOLE loop ...
    run();                                            // (w) ... and the genuine call AFTER it survives
}
void catchPre() {
    emit(1);                                          // (x) genuine call BEFORE the try ...
    try { throw Err2(); }
    catch (const Err2& emit) { (void)emit; }          //     the handler param covers the WHOLE handler ...
    emit(2);                                          // (x) ... and the genuine call AFTER it survives
}
void lamInitPre() {
    run();                                            // (y) genuine call BEFORE the lambda ...
    auto g = [run = 3]() { return run; };             //     the init-capture covers the WHOLE lambda body ...
    (void)g;
    run();                                            // (y) ... and the genuine call AFTER it survives
}
void siblingBlocks() {
    { int run = 1; (void)run; }                       // (z) two sibling shadowing blocks ...
    run();
    { int run = 2; (void)run; }
    run();                                            //     ... each claims only its own
}
EOF

cat >"$FIX/plain.cpp" <<'EOF'
// no-collision control: `total` names NO indexed symbol anywhere — its local sites must STAY listed
// (--uses on a plain local name is the external-answer feature writetargetcheck pins).
int consume(int x) { return x; }
void tally() {
    int total = 0;
    total += 4;
    consume(total);
}
EOF

echo "shadowcheck: BIN=$BIN  CORPUS=$FIX (generated)"

uses(){ "$BIN" "$FIX" --uses="$1" --no-cache 2>/dev/null | tr '>' '\n'; }
rows(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null | tr '>' '\n'; }

# ── (a) the shadowing function contributes NO site: --uses=run has nothing from shadowed.cpp ──────────
UR="$( uses run )"
printf '%s\n' "$UR" | grep -q 'shadowed.cpp' \
    && { no "--uses=run lists sites from shadowed.cpp — the local \`int run\` did not claim its scope"; printf '%s\n' "$UR" | grep 'shadowed.cpp'; } \
    || ok "--uses=run has ZERO sites from shadowed.cpp (local shadow claims the whole scope)"

# ── (b) zero recall loss: the genuine call in boss() is still listed, and --callers=run keeps boss ────
printf '%s\n' "$UR" | grep 'caller.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine role=call site in boss() (caller.cpp)" \
    || no "--uses=run LOST the genuine call in boss() — recall regression"
rows --callers=run | grep -q 'n="boss"' \
    && ok "--callers=run still lists boss (genuine edge intact)" \
    || no "--callers=run lost boss — the suppression over-reached into the call graph"

# ── (c) mixed body: local `process` suppressed, the genuine run() call in the SAME scope survives ─────
UP="$( uses process )"
printf '%s\n' "$UP" | grep -q 'mixed.cpp' \
    && { no "--uses=process lists sites from mixed.cpp — the shadowed local leaked through"; printf '%s\n' "$UP" | grep 'mixed.cpp'; } \
    || ok "--uses=process has ZERO sites from mixed.cpp (shadowed local suppressed)"
printf '%s\n' "$UP" | grep -q 'count="0"' \
    && ok "--uses=process count=\"0\" (no textual site anywhere belongs to the function)" \
    || no "--uses=process count is not 0 — a false site survives somewhere"
printf '%s\n' "$UR" | grep 'mixed.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call in tricky() — suppression of \`process\` never touched \`run\`" \
    || no "--uses=run LOST tricky()'s genuine call — suppression bled across names in one scope"
rows --callers=run | grep -q 'n="tricky"' \
    && ok "--callers=run still lists tricky (same-scope genuine edge intact)" \
    || no "--callers=run lost tricky — same-scope recall regression"

# ── (d) L3 fn-pointer discipline unchanged: `void (*cb)() = &run; cb();` still resolves its edge ──────
rows --callees=useCb | grep -q 'n="run"' \
    && ok "--callees=useCb resolves cb() to run (fn-binding var never shadow-suppressed)" \
    || no "--callees=useCb lost its run edge — the suppression broke the L3 fn-pointer resolve"

# ── (d2) no-collision control: a plain local with no same-named symbol keeps its --uses sites ─────────
UT="$( uses total )"
printf '%s\n' "$UT" | grep -q 'plain.cpp' \
    && ok "--uses=total (no indexed symbol named total) still lists the local's sites" \
    || no "--uses=total lost its sites — suppression fired without a name collision"

# ── (f)-(h) A5 fix round: reference declarators + structured bindings generate shadow evidence ────────
UK="$( uses key )"
for fn in refParam refLocal sbRange; do
    printf '%s\n' "$UK" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=key lists sites from $fn() — its shadowing declarator produced no evidence"; printf '%s\n' "$UK" | grep "in_id=\"$fn\""; } \
        || ok "--uses=key has ZERO sites from $fn() (reference/structured-binding declarator captured)"
done
printf '%s\n' "$UK" | grep 'refshapes.cpp' | grep -q 'role="call"' \
    && ok "--uses=key keeps the genuine call in keyCaller() (recall anchor intact)" \
    || no "--uses=key LOST keyCaller()'s genuine call — recall regression"

# ── (i) inner-block shadow: block-span suppression keeps the genuine call AFTER the block ─────────────
UR2="$( uses run )"
printf '%s\n' "$UR2" | grep 'innerblock.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps innerBlock()'s genuine post-block call (block-span, not whole-function)" \
    || no "--uses=run LOST innerBlock()'s genuine call after the shadowing block closed — silent recall loss"
printf '%s\n' "$UR2" | grep 'innerblock.cpp' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=run lists read/write sites from inside innerBlock()'s shadowing block"; printf '%s\n' "$UR2" | grep 'innerblock.cpp'; } \
    || ok "--uses=run has no read/write sites from innerBlock()'s shadowing block"
rows --callers=run | grep -q 'n="innerBlock"' \
    && ok "--callers=run lists innerBlock (the genuine edge resolved)" \
    || no "--callers=run lost innerBlock — the genuine post-block call minted no edge"

# ── (j)-(l) A5 addendum: lambda parameters, init-captures, and captured shadowing locals ──────────────
for fn in lamParam lamInit lamCap; do
    printf '%s\n' "$UK" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=key lists sites from $fn() — lambda-scope shadow evidence missing"; printf '%s\n' "$UK" | grep "in_id=\"$fn\""; } \
        || ok "--uses=key has ZERO sites from $fn() (lambda param/init-capture/captured-local suppressed)"
done

# ── (m)-(o) A5 iteration 3: header declarations scope to their control STATEMENT, never past it ───────
CTRL="$( uses run | grep 'ctrlinit.cpp' )"
forcalls="$( printf '%s\n' "$CTRL" | grep -c 'role="call".*in_id="forInit"' )"
[ "$forcalls" = "2" ] \
    && ok "--uses=run keeps BOTH genuine calls after forInit()'s loop (for-init scope stops at the loop)" \
    || { no "--uses=run has $forcalls of 2 genuine calls after forInit()'s loop — for-init scope leaked past the statement"; }
printf '%s\n' "$CTRL" | grep 'in_id="forInit"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=run lists read/write sites from inside forInit()'s loop"; printf '%s\n' "$CTRL" | grep 'in_id="forInit"'; } \
    || ok "--uses=run has no read/write sites from forInit()'s loop header/body"
printf '%s\n' "$CTRL" | grep 'in_id="ifInit"' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call after ifInit()'s if-init statement" \
    || no "--uses=run LOST the genuine call after ifInit() — if-init scope leaked past the statement"
printf '%s\n' "$CTRL" | grep 'in_id="whileCond"' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call after whileCond()'s loop" \
    || no "--uses=run LOST the genuine call after whileCond() — while-condition scope leaked past the statement"
for fn in ifInit whileCond; do
    printf '%s\n' "$CTRL" | grep "in_id=\"$fn\"" | grep -Eq 'role="(read|write)"' \
        && no "--uses=run lists read/write sites from inside $fn()'s statement" \
        || ok "--uses=run has no read/write sites from $fn()'s header/body"
done

# ── (p) A5 iteration 3: a catch parameter scopes to its handler block ─────────────────────────────────
UPC="$( uses process )"
printf '%s\n' "$UPC" | grep -q 'catchparam.cpp' \
    && { no "--uses=process lists sites from catcher()'s handler — catch param produced no evidence"; printf '%s\n' "$UPC" | grep 'catchparam.cpp'; } \
    || ok "--uses=process has ZERO sites from catcher()'s handler (catch param captured)"
uses run | grep 'catchparam.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps catcher()'s genuine call after the handler" \
    || no "--uses=run LOST catcher()'s genuine call — catch-param scope leaked past the handler"

# ── (q)-(u) A5 iteration 4: an ordinary block declaration shadows from its DECLARATION POINT ───────────
PRE="$( uses run | grep 'predecl.cpp' )"
printf '%s\n' "$PRE" | grep 'in_id="preDecl"' | grep -q 'role="call"' \
    && ok "--uses=run keeps preDecl()'s genuine call written ABOVE the shadowing local (declaration point)" \
    || no "--uses=run LOST preDecl()'s pre-declaration call — the span still starts at the block brace"
printf '%s\n' "$PRE" | grep 'in_id="preDecl"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=run lists read/write sites from preDecl() AFTER the declaration point"; printf '%s\n' "$PRE" | grep 'in_id="preDecl"'; } \
    || ok "--uses=run has no read/write sites from preDecl() after its declaration point"
rows --callers=run | grep -q 'n="preDecl"' \
    && ok "--callers=run lists preDecl (the pre-declaration call minted its genuine edge)" \
    || no "--callers=run lost preDecl — the recovered pre-declaration call minted no edge"
UPR="$( uses probe )"
printf '%s\n' "$UPR" | grep 'in_id="multiDecl"' | grep -q 'role="call"' \
    && ok "--uses=probe keeps multiDecl()'s call in the initializer BEFORE probe's own declarator" \
    || no "--uses=probe LOST multiDecl()'s pre-declarator call — same-statement ordering is not modelled"
printf '%s\n' "$UPR" | grep 'in_id="multiDecl"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=probe lists a read from multiDecl() AFTER probe's declarator — the point is the STATEMENT end, not the declarator's"; printf '%s\n' "$UPR" | grep 'in_id="multiDecl"'; } \
    || ok "--uses=probe has no read from multiDecl()'s later initializer (point = end of the complete declarator)"
printf '%s\n' "$UPR" | grep -q 'in_id="selfInit"' \
    && { no "--uses=probe lists a site from selfInit() — \`int probe = probe;\` initializer must be the LOCAL"; printf '%s\n' "$UPR" | grep 'in_id="selfInit"'; } \
    || ok "--uses=probe has ZERO sites from selfInit() (the initializer is inside the new name's scope)"
for fn in bareDecl bareDecl2; do
    printf '%s\n' "$PRE" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=run lists a site from $fn() — a plain declarator's own NAME leaked out as a read"; printf '%s\n' "$PRE" | grep "in_id=\"$fn\""; } \
        || ok "--uses=run has ZERO sites from $fn() (a declaration's every declarator field is a DECLARED name)"
done
# ── (q6)-(q9) declarator shapes arm 2's `declarator`-field probe cannot reach ──────────────────────────
for fn in optParam packParam attrDecl; do
    printf '%s\n' "$PRE" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=run lists a site from $fn() — a DECLARED name leaked out as a read of the fn it shadows"; printf '%s\n' "$PRE" | grep "in_id=\"$fn\""; } \
        || ok "--uses=run has ZERO sites from $fn() (defaulted/pack/attributed declarators are DECLARED names)"
done
printf '%s\n' "$UPR" | grep 'in_id="defaultCall"' | grep -q 'role="call"' \
    && ok "--uses=probe keeps defaultCall()'s call in a parameter's DEFAULT VALUE (only the declarator field is a decl site)" \
    || no "--uses=probe LOST defaultCall()'s default-value call — the defaulted-parameter arm suppressed too much"
USL="$( uses slot )"
printf '%s\n' "$USL" | grep 'in_id="sbDecl"' | grep -q 'role="call"' \
    && ok "--uses=slot keeps sbDecl()'s genuine call above the structured-binding declaration" \
    || no "--uses=slot LOST sbDecl()'s pre-declaration call — the binding's locus is not its identifier-list"
printf '%s\n' "$USL" | grep 'in_id="sbDecl"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=slot lists a read from sbDecl() after the structured binding"; printf '%s\n' "$USL" | grep 'in_id="sbDecl"'; } \
    || ok "--uses=slot has no read from sbDecl() after the structured binding"

# ── (v)-(z) A5 iteration 4 guards: whole-scope shapes keep their spans (no re-minted false positives) ──
GRD="$( uses run | grep 'scopeguards.cpp' )"
printf '%s\n' "$GRD" | grep -q 'in_id="paramFirst"' \
    && { no "--uses=run lists a site from paramFirst() — a definition parameter no longer covers the first body statement"; printf '%s\n' "$GRD" | grep 'in_id="paramFirst"'; } \
    || ok "--uses=run has ZERO sites from paramFirst() (a definition parameter keeps the whole-body span)"
for fn in rangeForPre lamInitPre siblingBlocks; do
    calls="$( printf '%s\n' "$GRD" | grep -c "role=\"call\".*in_id=\"$fn\"" )"
    [ "$calls" = "2" ] \
        && ok "--uses=run keeps BOTH genuine calls around $fn()'s shadowing scope" \
        || no "--uses=run has $calls of 2 genuine calls around $fn()'s shadowing scope"
    printf '%s\n' "$GRD" | grep "in_id=\"$fn\"" | grep -Eq 'role="(read|write)"' \
        && { no "--uses=run lists read/write sites from inside $fn()'s shadowing scope"; printf '%s\n' "$GRD" | grep "in_id=\"$fn\""; } \
        || ok "--uses=run has no read/write sites from inside $fn()'s shadowing scope"
done
UEM="$( uses emit )"
emitcalls="$( printf '%s\n' "$UEM" | grep -c 'role="call".*in_id="catchPre"' )"
[ "$emitcalls" = "2" ] \
    && ok "--uses=emit keeps BOTH genuine calls around catchPre()'s handler (catch param keeps its span)" \
    || no "--uses=emit has $emitcalls of 2 genuine calls around catchPre()'s handler"
printf '%s\n' "$UEM" | grep 'in_id="catchPre"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=emit lists read/write sites from inside catchPre()'s handler"; printf '%s\n' "$UEM" | grep 'in_id="catchPre"'; } \
    || ok "--uses=emit has no read/write sites from inside catchPre()'s handler"

# ── (e) determinism + well-formedness ─────────────────────────────────────────────────────────────────
A="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
B="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
[ "$A" = "$B" ] && ok "determinism (byte-identical run-to-run)" || no "non-deterministic --uses output"
C="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
D="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
[ "$C" = "$D" ] && ok "determinism (default map byte-identical run-to-run)" || no "non-deterministic default map"
if command -v xmllint >/dev/null 2>&1; then
    printf '%s' "$A" | xmllint --noout - 2>/dev/null && ok "--uses xml well-formed" || no "--uses xml malformed"
    printf '%s' "$C" | xmllint --noout - 2>/dev/null && ok "default map xml well-formed" || no "default map xml malformed"
else
    ok "xml well-formed (xmllint absent — skipped)"
fi

[ "$fail" -eq 0 ] && echo "ALL PASS" || echo "SOME FAILED"
exit "$fail"
