#!/usr/bin/env bash
# shadowcheck.sh — gate for local-shadow suppression (r9 loss bucket 2, kParserVer 52).
#
# The measured failure: a local variable that SHADOWS a function's name got its read/write/mention sites
# falsely attributed to the function — `int run = 0;` inside worker() put worker's `run` arithmetic into
# --uses=run (13 false sites on one r9 query). Post-round, a reference site to name N inside a function
# whose LOCAL DECLARATIONS bind N as a variable is NOT attributed to any indexed symbol named N (the local
# wins for the whole scope — C++ name lookup). Guards this gate pins alongside the suppression itself:
#   * ZERO recall loss on genuine calls: a real run() call in another function — and in the SAME function
#     as an unrelated shadow — must survive;
#   * the L3 fn-pointer discipline is untouched: `void (*cb)() = &run; cb();` still resolves its edge (a
#     fn-binding var's references are calls THROUGH the variable, never suppressed);
#   * the no-collision feature survives: --uses on a plain local name with NO same-named indexed symbol
#     (writetargetcheck's whole contract) still lists its sites — suppression needs a collision.
#
# The fixture is GENERATED here (self-contained; nothing committed under test/).
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/shadowcheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/shadowfix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/funcs.h" <<'EOF'
// shadow gate fixture — generated by test/shadowcheck.sh, never committed.
void run();
void process(int v);
EOF

cat >"$FIX/funcs.cpp" <<'EOF'
#include "funcs.h"
void run() {}
void process(int v) { (void)v; }
EOF

cat >"$FIX/shadowed.cpp" <<'EOF'
#include "funcs.h"
int use(int x) { return x; }
void worker() {
    int run = 0;      // the LOCAL shadows function run() for this whole scope
    run += 1;
    int y = run + 2;
    use(run);
    use(y);
}
EOF

cat >"$FIX/caller.cpp" <<'EOF'
#include "funcs.h"
void boss() {
    run();            // a GENUINE call — zero recall loss is the bar
}
EOF

cat >"$FIX/mixed.cpp" <<'EOF'
#include "funcs.h"
void tricky() {
    int process = 0;  // shadows process() ...
    process += 3;     // ... so these sites are the local's
    run();            // ... while THIS genuine call must survive in the same scope
    (void)process;
}
EOF

cat >"$FIX/fnptr.cpp" <<'EOF'
#include "funcs.h"
void useCb() {
    void (*cb)() = &run;   // an L3 fn-binding var — cb's references are calls THROUGH the variable
    cb();                  // must still resolve to run() (never shadow-suppressed)
}
EOF

cat >"$FIX/refshapes.cpp" <<'EOF'
// A5 fix-round arms: reference declarators, structured bindings, inner-block spans, lambdas.
struct Pr { int key; int w; };
void key();            // the shadowed function (defined in funcs2.cpp)
void keyCaller() { key(); }                                        // genuine call — recall anchor
int  refParam(const int& key) { int x = key; return x; }           // (f) pass-by-const-ref param shadow
void refLocal() { int g0 = 0; int& key = g0; (void)key; }          // (g) reference-typed local shadow
void sbRange() { Pr ps[2] = {}; for (const auto& [key, w] : ps) { (void)key; (void)w; } }  // (h)
void lamParam() { auto f = [](int key) { return key + 1; }; (void)f; }        // (j) lambda param shadow
void lamInit()  { auto g = [key = 3]() { return key; }; (void)g; }            // (k) init-capture shadow
void lamCap()   { int key = 1; auto h = [key]() { return key; }; (void)h; }   // (l) simple capture of a shadowing local
EOF

cat >"$FIX/funcs2.cpp" <<'EOF'
void key() {}
EOF

cat >"$FIX/innerblock.cpp" <<'EOF'
#include "funcs.h"
void innerBlock() {
    {
        int run = 0;   // shadows run() INSIDE THIS BLOCK only
        run += 1;
    }
    run();             // (i) a GENUINE call after the block closes — block-span suppression must keep it
}
EOF

cat >"$FIX/ctrlinit.cpp" <<'EOF'
// A5 iteration-3 arms: control-statement HEADER declarations scope to the STATEMENT, not the enclosing block.
#include "funcs.h"
int  getVal();
void forInit() {
    for (int run = 0; run < 3; ++run) { (void)run; }   // header decl + body use — all suppressed
    run();                                             // (m) TWO genuine calls after the loop — both survive
    run();
}
void ifInit() {
    if (int run = getVal()) { (void)run; }             // (n) if-init variant
    run();
}
void whileCond() {
    while (int run = getVal()) { (void)run; }          // (o) while-condition variant
    run();
}
EOF

cat >"$FIX/catchparam.cpp" <<'EOF'
#include "funcs.h"
struct Error { };
void catcher() {
    try { throw Error(); }
    catch (const Error& process) {                     // (p) catch param shadows process()
        (void)process;
    }
    run();
}
EOF

cat >"$FIX/plain.cpp" <<'EOF'
// no-collision control: `total` names NO indexed symbol anywhere — its local sites must STAY listed
// (--uses on a plain local name is the external-answer feature writetargetcheck pins).
int consume(int x) { return x; }
void tally() {
    int total = 0;
    total += 4;
    consume(total);
}
EOF

echo "shadowcheck: BIN=$BIN  CORPUS=$FIX (generated)"

uses(){ "$BIN" "$FIX" --uses="$1" --no-cache 2>/dev/null | tr '>' '\n'; }
rows(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null | tr '>' '\n'; }

# ── (a) the shadowing function contributes NO site: --uses=run has nothing from shadowed.cpp ──────────
UR="$( uses run )"
printf '%s\n' "$UR" | grep -q 'shadowed.cpp' \
    && { no "--uses=run lists sites from shadowed.cpp — the local \`int run\` did not claim its scope"; printf '%s\n' "$UR" | grep 'shadowed.cpp'; } \
    || ok "--uses=run has ZERO sites from shadowed.cpp (local shadow claims the whole scope)"

# ── (b) zero recall loss: the genuine call in boss() is still listed, and --callers=run keeps boss ────
printf '%s\n' "$UR" | grep 'caller.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine role=call site in boss() (caller.cpp)" \
    || no "--uses=run LOST the genuine call in boss() — recall regression"
rows --callers=run | grep -q 'n="boss"' \
    && ok "--callers=run still lists boss (genuine edge intact)" \
    || no "--callers=run lost boss — the suppression over-reached into the call graph"

# ── (c) mixed body: local `process` suppressed, the genuine run() call in the SAME scope survives ─────
UP="$( uses process )"
printf '%s\n' "$UP" | grep -q 'mixed.cpp' \
    && { no "--uses=process lists sites from mixed.cpp — the shadowed local leaked through"; printf '%s\n' "$UP" | grep 'mixed.cpp'; } \
    || ok "--uses=process has ZERO sites from mixed.cpp (shadowed local suppressed)"
printf '%s\n' "$UP" | grep -q 'count="0"' \
    && ok "--uses=process count=\"0\" (no textual site anywhere belongs to the function)" \
    || no "--uses=process count is not 0 — a false site survives somewhere"
printf '%s\n' "$UR" | grep 'mixed.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call in tricky() — suppression of \`process\` never touched \`run\`" \
    || no "--uses=run LOST tricky()'s genuine call — suppression bled across names in one scope"
rows --callers=run | grep -q 'n="tricky"' \
    && ok "--callers=run still lists tricky (same-scope genuine edge intact)" \
    || no "--callers=run lost tricky — same-scope recall regression"

# ── (d) L3 fn-pointer discipline unchanged: `void (*cb)() = &run; cb();` still resolves its edge ──────
rows --callees=useCb | grep -q 'n="run"' \
    && ok "--callees=useCb resolves cb() to run (fn-binding var never shadow-suppressed)" \
    || no "--callees=useCb lost its run edge — the suppression broke the L3 fn-pointer resolve"

# ── (d2) no-collision control: a plain local with no same-named symbol keeps its --uses sites ─────────
UT="$( uses total )"
printf '%s\n' "$UT" | grep -q 'plain.cpp' \
    && ok "--uses=total (no indexed symbol named total) still lists the local's sites" \
    || no "--uses=total lost its sites — suppression fired without a name collision"

# ── (f)-(h) A5 fix round: reference declarators + structured bindings generate shadow evidence ────────
UK="$( uses key )"
for fn in refParam refLocal sbRange; do
    printf '%s\n' "$UK" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=key lists sites from $fn() — its shadowing declarator produced no evidence"; printf '%s\n' "$UK" | grep "in_id=\"$fn\""; } \
        || ok "--uses=key has ZERO sites from $fn() (reference/structured-binding declarator captured)"
done
printf '%s\n' "$UK" | grep 'refshapes.cpp' | grep -q 'role="call"' \
    && ok "--uses=key keeps the genuine call in keyCaller() (recall anchor intact)" \
    || no "--uses=key LOST keyCaller()'s genuine call — recall regression"

# ── (i) inner-block shadow: block-span suppression keeps the genuine call AFTER the block ─────────────
UR2="$( uses run )"
printf '%s\n' "$UR2" | grep 'innerblock.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps innerBlock()'s genuine post-block call (block-span, not whole-function)" \
    || no "--uses=run LOST innerBlock()'s genuine call after the shadowing block closed — silent recall loss"
printf '%s\n' "$UR2" | grep 'innerblock.cpp' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=run lists read/write sites from inside innerBlock()'s shadowing block"; printf '%s\n' "$UR2" | grep 'innerblock.cpp'; } \
    || ok "--uses=run has no read/write sites from innerBlock()'s shadowing block"
rows --callers=run | grep -q 'n="innerBlock"' \
    && ok "--callers=run lists innerBlock (the genuine edge resolved)" \
    || no "--callers=run lost innerBlock — the genuine post-block call minted no edge"

# ── (j)-(l) A5 addendum: lambda parameters, init-captures, and captured shadowing locals ──────────────
for fn in lamParam lamInit lamCap; do
    printf '%s\n' "$UK" | grep -q "in_id=\"$fn\"" \
        && { no "--uses=key lists sites from $fn() — lambda-scope shadow evidence missing"; printf '%s\n' "$UK" | grep "in_id=\"$fn\""; } \
        || ok "--uses=key has ZERO sites from $fn() (lambda param/init-capture/captured-local suppressed)"
done

# ── (m)-(o) A5 iteration 3: header declarations scope to their control STATEMENT, never past it ───────
CTRL="$( uses run | grep 'ctrlinit.cpp' )"
forcalls="$( printf '%s\n' "$CTRL" | grep -c 'role="call".*in_id="forInit"' )"
[ "$forcalls" = "2" ] \
    && ok "--uses=run keeps BOTH genuine calls after forInit()'s loop (for-init scope stops at the loop)" \
    || { no "--uses=run has $forcalls of 2 genuine calls after forInit()'s loop — for-init scope leaked past the statement"; }
printf '%s\n' "$CTRL" | grep 'in_id="forInit"' | grep -Eq 'role="(read|write)"' \
    && { no "--uses=run lists read/write sites from inside forInit()'s loop"; printf '%s\n' "$CTRL" | grep 'in_id="forInit"'; } \
    || ok "--uses=run has no read/write sites from forInit()'s loop header/body"
printf '%s\n' "$CTRL" | grep 'in_id="ifInit"' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call after ifInit()'s if-init statement" \
    || no "--uses=run LOST the genuine call after ifInit() — if-init scope leaked past the statement"
printf '%s\n' "$CTRL" | grep 'in_id="whileCond"' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call after whileCond()'s loop" \
    || no "--uses=run LOST the genuine call after whileCond() — while-condition scope leaked past the statement"
for fn in ifInit whileCond; do
    printf '%s\n' "$CTRL" | grep "in_id=\"$fn\"" | grep -Eq 'role="(read|write)"' \
        && no "--uses=run lists read/write sites from inside $fn()'s statement" \
        || ok "--uses=run has no read/write sites from $fn()'s header/body"
done

# ── (p) A5 iteration 3: a catch parameter scopes to its handler block ─────────────────────────────────
UPC="$( uses process )"
printf '%s\n' "$UPC" | grep -q 'catchparam.cpp' \
    && { no "--uses=process lists sites from catcher()'s handler — catch param produced no evidence"; printf '%s\n' "$UPC" | grep 'catchparam.cpp'; } \
    || ok "--uses=process has ZERO sites from catcher()'s handler (catch param captured)"
uses run | grep 'catchparam.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps catcher()'s genuine call after the handler" \
    || no "--uses=run LOST catcher()'s genuine call — catch-param scope leaked past the handler"

# ── (e) determinism + well-formedness ─────────────────────────────────────────────────────────────────
A="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
B="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
[ "$A" = "$B" ] && ok "determinism (byte-identical run-to-run)" || no "non-deterministic --uses output"
C="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
D="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
[ "$C" = "$D" ] && ok "determinism (default map byte-identical run-to-run)" || no "non-deterministic default map"
if command -v xmllint >/dev/null 2>&1; then
    printf '%s' "$A" | xmllint --noout - 2>/dev/null && ok "--uses xml well-formed" || no "--uses xml malformed"
    printf '%s' "$C" | xmllint --noout - 2>/dev/null && ok "default map xml well-formed" || no "default map xml malformed"
else
    ok "xml well-formed (xmllint absent — skipped)"
fi

[ "$fail" -eq 0 ] && echo "ALL PASS" || echo "SOME FAILED"
exit "$fail"
