#!/usr/bin/env bash
# shadowcheck.sh — gate for local-shadow suppression (r9 loss bucket 2, kParserVer 52).
#
# The measured failure: a local variable that SHADOWS a function's name got its read/write/mention sites
# falsely attributed to the function — `int run = 0;` inside worker() put worker's `run` arithmetic into
# --uses=run (13 false sites on one r9 query). Post-round, a reference site to name N inside a function
# whose LOCAL DECLARATIONS bind N as a variable is NOT attributed to any indexed symbol named N (the local
# wins for the whole scope — C++ name lookup). Guards this gate pins alongside the suppression itself:
#   * ZERO recall loss on genuine calls: a real run() call in another function — and in the SAME function
#     as an unrelated shadow — must survive;
#   * the L3 fn-pointer discipline is untouched: `void (*cb)() = &run; cb();` still resolves its edge (a
#     fn-binding var's references are calls THROUGH the variable, never suppressed);
#   * the no-collision feature survives: --uses on a plain local name with NO same-named indexed symbol
#     (writetargetcheck's whole contract) still lists its sites — suppression needs a collision.
#
# The fixture is GENERATED here (self-contained; nothing committed under test/).
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/shadowcheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/shadowfix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/funcs.h" <<'EOF'
// shadow gate fixture — generated by test/shadowcheck.sh, never committed.
void run();
void process(int v);
EOF

cat >"$FIX/funcs.cpp" <<'EOF'
#include "funcs.h"
void run() {}
void process(int v) { (void)v; }
EOF

cat >"$FIX/shadowed.cpp" <<'EOF'
#include "funcs.h"
int use(int x) { return x; }
void worker() {
    int run = 0;      // the LOCAL shadows function run() for this whole scope
    run += 1;
    int y = run + 2;
    use(run);
    use(y);
}
EOF

cat >"$FIX/caller.cpp" <<'EOF'
#include "funcs.h"
void boss() {
    run();            // a GENUINE call — zero recall loss is the bar
}
EOF

cat >"$FIX/mixed.cpp" <<'EOF'
#include "funcs.h"
void tricky() {
    int process = 0;  // shadows process() ...
    process += 3;     // ... so these sites are the local's
    run();            // ... while THIS genuine call must survive in the same scope
    (void)process;
}
EOF

cat >"$FIX/fnptr.cpp" <<'EOF'
#include "funcs.h"
void useCb() {
    void (*cb)() = &run;   // an L3 fn-binding var — cb's references are calls THROUGH the variable
    cb();                  // must still resolve to run() (never shadow-suppressed)
}
EOF

cat >"$FIX/plain.cpp" <<'EOF'
// no-collision control: `total` names NO indexed symbol anywhere — its local sites must STAY listed
// (--uses on a plain local name is the external-answer feature writetargetcheck pins).
int consume(int x) { return x; }
void tally() {
    int total = 0;
    total += 4;
    consume(total);
}
EOF

echo "shadowcheck: BIN=$BIN  CORPUS=$FIX (generated)"

uses(){ "$BIN" "$FIX" --uses="$1" --no-cache 2>/dev/null | tr '>' '\n'; }
rows(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null | tr '>' '\n'; }

# ── (a) the shadowing function contributes NO site: --uses=run has nothing from shadowed.cpp ──────────
UR="$( uses run )"
printf '%s\n' "$UR" | grep -q 'shadowed.cpp' \
    && { no "--uses=run lists sites from shadowed.cpp — the local \`int run\` did not claim its scope"; printf '%s\n' "$UR" | grep 'shadowed.cpp'; } \
    || ok "--uses=run has ZERO sites from shadowed.cpp (local shadow claims the whole scope)"

# ── (b) zero recall loss: the genuine call in boss() is still listed, and --callers=run keeps boss ────
printf '%s\n' "$UR" | grep 'caller.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine role=call site in boss() (caller.cpp)" \
    || no "--uses=run LOST the genuine call in boss() — recall regression"
rows --callers=run | grep -q 'n="boss"' \
    && ok "--callers=run still lists boss (genuine edge intact)" \
    || no "--callers=run lost boss — the suppression over-reached into the call graph"

# ── (c) mixed body: local `process` suppressed, the genuine run() call in the SAME scope survives ─────
UP="$( uses process )"
printf '%s\n' "$UP" | grep -q 'mixed.cpp' \
    && { no "--uses=process lists sites from mixed.cpp — the shadowed local leaked through"; printf '%s\n' "$UP" | grep 'mixed.cpp'; } \
    || ok "--uses=process has ZERO sites from mixed.cpp (shadowed local suppressed)"
printf '%s\n' "$UP" | grep -q 'count="0"' \
    && ok "--uses=process count=\"0\" (no textual site anywhere belongs to the function)" \
    || no "--uses=process count is not 0 — a false site survives somewhere"
printf '%s\n' "$UR" | grep 'mixed.cpp' | grep -q 'role="call"' \
    && ok "--uses=run keeps the genuine call in tricky() — suppression of \`process\` never touched \`run\`" \
    || no "--uses=run LOST tricky()'s genuine call — suppression bled across names in one scope"
rows --callers=run | grep -q 'n="tricky"' \
    && ok "--callers=run still lists tricky (same-scope genuine edge intact)" \
    || no "--callers=run lost tricky — same-scope recall regression"

# ── (d) L3 fn-pointer discipline unchanged: `void (*cb)() = &run; cb();` still resolves its edge ──────
rows --callees=useCb | grep -q 'n="run"' \
    && ok "--callees=useCb resolves cb() to run (fn-binding var never shadow-suppressed)" \
    || no "--callees=useCb lost its run edge — the suppression broke the L3 fn-pointer resolve"

# ── (d2) no-collision control: a plain local with no same-named symbol keeps its --uses sites ─────────
UT="$( uses total )"
printf '%s\n' "$UT" | grep -q 'plain.cpp' \
    && ok "--uses=total (no indexed symbol named total) still lists the local's sites" \
    || no "--uses=total lost its sites — suppression fired without a name collision"

# ── (e) determinism + well-formedness ─────────────────────────────────────────────────────────────────
A="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
B="$( "$BIN" "$FIX" --uses=run --no-cache 2>/dev/null )"
[ "$A" = "$B" ] && ok "determinism (byte-identical run-to-run)" || no "non-deterministic --uses output"
C="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
D="$( "$BIN" "$FIX" --no-cache 2>/dev/null )"
[ "$C" = "$D" ] && ok "determinism (default map byte-identical run-to-run)" || no "non-deterministic default map"
if command -v xmllint >/dev/null 2>&1; then
    printf '%s' "$A" | xmllint --noout - 2>/dev/null && ok "--uses xml well-formed" || no "--uses xml malformed"
    printf '%s' "$C" | xmllint --noout - 2>/dev/null && ok "default map xml well-formed" || no "default map xml malformed"
else
    ok "xml well-formed (xmllint absent — skipped)"
fi

[ "$fail" -eq 0 ] && echo "ALL PASS" || echo "SOME FAILED"
exit "$fail"
