#!/usr/bin/env bash
# usingdeclcheck.sh — gate for using-declaration re-export references (r9 loss bucket 1).
#
# The measured gap this closes: a C++ `using ns::name;` re-export contributed NO --uses row at all — the
# site was invisible to the use-site index even though call RESOLUTION through the re-exported name already
# worked. Post-lever, the using-declaration site is a role="import" use-site of the target (the EXISTING
# import role — no new vocabulary), minted by the new @reference.import pattern in queries/cpp/tags.scm and
# routed in ingest.cpp's tags pass. Import refs NEVER enter the call graph (graph.h admits Call+Macro only),
# so a never-called re-export gains the row and no edge.
#
# COVERED: `using ns::name;` at namespace scope, inside a namespace body, at class scope
# (`using Base::method;` — the same using_declaration node kind), and 3+-segment targets (`using a::b::c;`,
# re-split by the existing H4 name/qualifier logic). NOT covered, by design, and pinned negative below:
# `using namespace ns;` directives (no single-symbol target — including the qualified spelling
# `using namespace lib::nested;`, which the tags pattern matches and ingest.cpp's
# usingDeclarationIsDirective drops), `using enum E;` (C++20 — re-exports the ENUMERATORS, not the named
# type), and `using alias = type;` type aliases (a different node kind, alias_declaration, never matched).
#
# The fixture is GENERATED here (self-contained; nothing committed under test/):
#   udlib.h    — namespace rw_ud { doThing / calcVal / neverUsed }, namespace rw_ud::inner { innerFn }.
#   udlib.cpp  — trivial definitions.
#   udapi.h    — the re-exports: using rw_ud::doThing; using rw_ud::calcVal; using rw_ud::neverUsed;
#                a namespace-body re-export (namespace udapi { using rw_ud::doThing; }), and the
#                class-scope form (struct UdDeriv : UdBase { using UdBase::baseFn; }).
#   udmain.cpp — calls through the re-exported names (resolution must SURVIVE), plus the three negative
#                controls: using namespace rw_ud; / using namespace rw_ud::inner; / using UdAlias = UdSomeType;
#
# Usage:  RIPWIRE_BIN=build/ripwire bash test/usingdeclcheck.sh   (or asan/ripwire)
# Exits non-zero on any failure; prints PASS/FAIL per check, ALL PASS on success.

set -u
ROOT="$( cd "$( dirname "$0" )/.." && pwd )"
BIN="${RIPWIRE_BIN:-$ROOT/build/ripwire}"
[ "${BIN#/}" = "$BIN" ] && BIN="$ROOT/$BIN"          # allow a repo-relative RIPWIRE_BIN
TMP="$( mktemp -d )"; trap 'rm -rf "$TMP"' EXIT
FIX="$TMP/usingfix"
mkdir -p "$FIX"
fail=0
ok(){ printf '  PASS  %s\n' "$*"; }
no(){ printf '  FAIL  %s\n' "$*"; fail=1; }

[ -x "$BIN" ] || { echo "no ripwire binary at $BIN — build first (cmake --build build -j)"; exit 2; }
cd "$ROOT"

cat >"$FIX/udlib.h" <<'EOF'
// usingdecl gate fixture — generated by test/usingdeclcheck.sh, never committed.
namespace rw_ud
{
    void doThing();
    int  calcVal( int x );
    void neverUsed();
    namespace inner
    {
        void innerFn();
    }
}
struct UdBase
{
    void baseFn();
};
EOF

cat >"$FIX/udapi.h" <<'EOF'
// usingdecl gate fixture — generated by test/usingdeclcheck.sh, never committed.
#include "udlib.h"
using rw_ud::doThing;
using rw_ud::calcVal;
using rw_ud::neverUsed;
namespace udapi
{
    using rw_ud::doThing;
}
struct UdDeriv : UdBase
{
    using UdBase::baseFn;
};
EOF

cat >"$FIX/udlib.cpp" <<'EOF'
// usingdecl gate fixture — generated by test/usingdeclcheck.sh, never committed.
#include "udlib.h"
void rw_ud::doThing() { }
int  rw_ud::calcVal( int x ) { return x + 1; }
void rw_ud::neverUsed() { }
void rw_ud::inner::innerFn() { }
void UdBase::baseFn() { }
EOF

cat >"$FIX/udmain.cpp" <<'EOF'
// usingdecl gate fixture — generated by test/usingdeclcheck.sh, never committed.
#include "udapi.h"
using namespace rw_ud;
using namespace rw_ud::inner;
struct UdSomeType { int v; };
using UdAlias = UdSomeType;
int driver()
{
    doThing();
    return calcVal( 2 );
}
EOF

echo "usingdeclcheck: BIN=$BIN  CORPUS=$FIX (generated)"

verb(){ "$BIN" "$FIX" "$1" --no-cache 2>/dev/null; }

# ── (a) the re-export site is a role="import" use-site of the target, at the using-declaration's own line. ──
UD="$( verb --uses=doThing )"
printf '%s' "$UD" | grep -q '<u role="import" p="[^"]*udapi.h:3"' \
    && ok "--uses=doThing shows role=\"import\" at udapi.h:3 (the top-level using-declaration site)" \
    || no "--uses=doThing has no role=\"import\" row at udapi.h:3: $( printf '%s' "$UD" | grep -o '<uses [^>]*' | head -1 )"
printf '%s' "$UD" | grep -q '<u role="import" p="[^"]*udapi.h:8"' \
    && ok "--uses=doThing shows role=\"import\" at udapi.h:8 (the namespace-BODY re-export site)" \
    || no "--uses=doThing has no role=\"import\" row at udapi.h:8 (namespace-body using-declaration missed)"
CV="$( verb --uses=calcVal )"
printf '%s' "$CV" | grep -q '<u role="import" p="[^"]*udapi.h:4"' \
    && ok "--uses=calcVal shows role=\"import\" at udapi.h:4" \
    || no "--uses=calcVal has no role=\"import\" row at udapi.h:4"

# ── (a-bis) the class-scope form: `using UdBase::baseFn;` is the same node kind and is covered. ──
verb --uses=baseFn | grep -q '<u role="import" p="[^"]*udapi.h:12"' \
    && ok "--uses=baseFn shows role=\"import\" at udapi.h:12 (class-scope using-declaration)" \
    || no "--uses=baseFn has no role=\"import\" row at udapi.h:12 (class-scope form missed)"

# ── (b) call resolution through the re-exported name SURVIVES (the pre-lever behavior, preserved). ──
CE="$( verb --callees=driver )"
printf '%s' "$CE" | grep -q 'n="doThing"' \
    && ok "--callees=driver still lists doThing (resolution through the re-export unbroken)" \
    || no "--callees=driver lost doThing — the lever broke call resolution"
printf '%s' "$CE" | grep -q 'n="calcVal"' \
    && ok "--callees=driver still lists calcVal" \
    || no "--callees=driver lost calcVal"
printf '%s' "$UD" | grep -q '<u role="call" p="[^"]*udmain.cpp:9"' \
    && ok "--uses=doThing keeps the role=\"call\" site at udmain.cpp:9 alongside the import rows" \
    || no "--uses=doThing lost the role=\"call\" site at udmain.cpp:9"

# ── (c) negative: `using namespace x;` mints NO import row — bare and qualified spellings both. ──
verb --uses=rw_ud | grep -q '<u role="import"' \
    && no "--uses=rw_ud shows a role=\"import\" row — 'using namespace rw_ud;' must not mint one (no single-symbol target)" \
    || ok "'using namespace rw_ud;' mints no import row"
verb --uses=inner | grep -q '<u role="import"' \
    && no "--uses=inner shows a role=\"import\" row — 'using namespace rw_ud::inner;' must not mint one (qualified directive)" \
    || ok "'using namespace rw_ud::inner;' mints no import row (the qualified directive is dropped at capture time)"
verb --uses=innerFn | grep -q '<u role="import"' \
    && no "--uses=innerFn shows a role=\"import\" row — a namespace directive must not fan out to members" \
    || ok "the directive's namespace members gain no import rows either"

# ── (d) negative: `using UdAlias = UdSomeType;` is an alias_declaration, not a re-export — pinned to
#        today's behavior: no import row for the aliased type. ──
verb --uses=UdSomeType | grep -q '<u role="import"' \
    && no "--uses=UdSomeType shows a role=\"import\" row — a type alias is not a re-export" \
    || ok "'using UdAlias = UdSomeType;' mints no import row (alias_declaration never matches)"

# ── (e) a NEVER-CALLED re-export gains the import row but NO call edge (import refs never enter the graph). ──
NU="$( verb --uses=neverUsed )"
printf '%s' "$NU" | grep -q '<u role="import" p="[^"]*udapi.h:5"' \
    && ok "--uses=neverUsed shows role=\"import\" at udapi.h:5 (the row exists without any call)" \
    || no "--uses=neverUsed has no role=\"import\" row at udapi.h:5"
printf '%s' "$NU" | grep -q '<u role="call"' \
    && no "--uses=neverUsed shows a role=\"call\" site — the import ref leaked into call territory" \
    || ok "--uses=neverUsed has no role=\"call\" site"
verb --callers=neverUsed | grep -q 'count="0"' \
    && ok "--callers=neverUsed reports count=\"0\" (the import row minted no call edge)" \
    || no "--callers=neverUsed is non-zero — an import ref entered the call graph"

# ── verdict ──
if [ "$fail" -eq 0 ]; then
    echo "usingdeclcheck: ALL PASS"
    exit 0
fi
echo "usingdeclcheck: FAILURES above"
exit 1
