#!/usr/bin/env python3
"""
Unit tests for bench/locbench/crossctx_sites.py — the mechanical stage of the cross-context external-rate
pre-registration (docs/research/cross-context-external-rate.md, 2026-09-23).

SYNTHETIC ONLY. Every patch and every "pre-fix file" below is hand-written in this file. Nothing reads
Loc-Bench data, invokes git or the ripwire binary, or touches the network. The pre-registration requires
that no row be scored before the recipe is committed; these tests exist to prove the recipe's MECHANICS
(diff parsing, path classes, line→definition mapping, the legacy fingerprint rule, the sampler, kappa,
Wilson, the post-stratified estimate and the decision table) on data invented for the purpose — and to
pin the frozen constants so a later edit fails a test instead of moving silently.

Pure Python, no pytest dependency — same convention as test_compare_gate.py. Runs as a plain script:

    python3 bench/locbench/test_crossctx_sites.py
"""
import os, sys

HERE = os.path.dirname( os.path.abspath( __file__ ) )
sys.path.insert( 0, HERE )
import crossctx_sites as X

# ── a hand-written pre-fix module ─────────────────────────────────────────────────────────────────────────
BASE = """\
import os

LIMIT = 3

def helper(x):
    return x + 1

class Widget:
    kind = "w"

    @property
    def size(self):
        def inner(v):
            return v * 2
        return inner(self._n)

    def grow(self, n):
        self._n = n

def tail():
    return LIMIT
"""
# line numbers: 1 import, 3 LIMIT, 5-6 helper, 8 class, 9 kind, 11 @property, 12-15 size (inner 13-14), 17-18 grow, 20-21 tail

def read_base( files ):
    return lambda p: files.get( p )

def diff( path, hunks, new_path=None, rename=False ):
    out = [ "diff --git a/%s b/%s" % ( path, new_path or path ) ]
    if rename:
        out += [ "similarity index 90%", "rename from %s" % path, "rename to %s" % new_path ]
    out += [ "--- a/%s" % path, "+++ b/%s" % ( new_path or path ) ]
    for hdr, lines in hunks:
        out.append( hdr ); out.extend( lines )
    return "\n".join( out ) + "\n"

# ── legacy fingerprint rule ───────────────────────────────────────────────────────────────────────────────
def test_legacy_shape_counts_tests_as_source_and_hunks_in_first_file():
    one = diff( "pkg/a.py", [ ( "@@ -5,2 +5,2 @@", [ " def helper(x):", "-    return x + 1", "+    return x + 2" ] ) ] )
    assert X.legacy_shape( one ) == "LOCAL"
    two_hunks = diff( "pkg/a.py", [ ( "@@ -5,2 +5,2 @@", [ "-a", "+b" ] ), ( "@@ -17,2 +17,2 @@", [ "-c", "+d" ] ) ] )
    assert X.legacy_shape( two_hunks ) == "SPREAD-IN-FILE"
    with_test = one + diff( "tests/test_a.py", [ ( "@@ -1,1 +1,2 @@", [ " x", "+y" ] ) ] )
    assert X.legacy_shape( with_test ) == "CROSS", "the legacy rule does NOT exclude tests — that is the point of reproducing it"
    assert X.legacy_shape( diff( "docs/x.rst", [ ( "@@ -1,1 +1,1 @@", [ "-a", "+b" ] ) ] ) ) is None

def test_fingerprint_passes_only_on_the_pinned_counts():
    rows = [ dict( patch=diff( "a.py", [ ( "@@ -1,1 +1,1 @@", [ "-a", "+b" ] ) ] ) ) ]
    counts, ok = X.fingerprint( rows )
    assert counts == { "CROSS": 0, "SPREAD-IN-FILE": 0, "LOCAL": 1 } and not ok
    assert X.FROZEN[ "fingerprint" ] == { "CROSS": 94, "SPREAD-IN-FILE": 254, "LOCAL": 212 }

# ── M1 parse ──────────────────────────────────────────────────────────────────────────────────────────────
def test_parse_patch_hunks_and_rename():
    p = diff( "pkg/a.py", [ ( "@@ -5,2 +5,3 @@ def helper", [ " def helper(x):", "-    return x + 1", "+    y = 1", "+    return x + y" ] ) ] ) \
      + diff( "pkg/old.py", [], new_path="pkg/new.py", rename=True )
    fds = X.parse_patch( p )
    assert [ f.old_path for f in fds ] == [ "pkg/a.py", "pkg/old.py" ]
    assert fds[ 0 ].hunks[ 0 ].old_start == 5 and fds[ 0 ].hunks[ 0 ].old_len == 2 and len( fds[ 0 ].hunks[ 0 ].lines ) == 4
    assert fds[ 1 ].is_rename and fds[ 1 ].new_path == "pkg/new.py" and fds[ 1 ].hunks == []

# ── M2 classify ───────────────────────────────────────────────────────────────────────────────────────────
def test_classify_path_first_match_wins():
    assert X.classify_path( "tests/unit/test_x.py" ) == "TEST"
    assert X.classify_path( "pkg/conftest.py" ) == "TEST"
    assert X.classify_path( "pkg/x_test.py" ) == "TEST"
    assert X.classify_path( "docs/index.rst" ) == "DOC"
    assert X.classify_path( "CHANGELOG.rst" ) == "DOC"
    assert X.classify_path( "changelog.d/123.bugfix" ) == "DOC"
    assert X.classify_path( "app/migrations/0004_auto.py" ) == "GENERATED"
    assert X.classify_path( "pkg/_version.py" ) == "GENERATED"
    assert X.classify_path( "pkg/gen.py", [ "# this file is GENERATED by foo", "", "" ] ) == "GENERATED"
    assert X.classify_path( "pkg/core.py" ) == "SOURCE"
    assert X.classify_path( "pkg/core.pyi" ) == "SOURCE"
    assert X.classify_path( "ext/fast.c" ) == "OTHERLANG"
    assert X.classify_path( "setup.cfg" ) == "NONSOURCE"
    assert X.classify_path( "tests/data/fixture.py" ) == "TEST", "tests/ wins over .py"

# ── M3 changed lines ──────────────────────────────────────────────────────────────────────────────────────
def test_changed_old_lines_removed_and_pure_insertion_anchor():
    h = X.Hunk( 5, 3, [ " a", "-b", " c", "-d" ] )
    assert X.changed_old_lines( h ) == { 6, 8 }
    ins = X.Hunk( 10, 2, [ " a", " b", "+c", "+d" ] )           # insertion after old line 11
    assert X.changed_old_lines( ins ) == { 11 }
    top = X.Hunk( 1, 2, [ "+c", " a", " b" ] )                  # insertion at the top of a non-empty file
    assert X.changed_old_lines( top ) == { 1 }
    empty = X.Hunk( 0, 0, [ "+c", "+d" ] )                      # new content in an empty file
    assert X.changed_old_lines( empty ) == { 0 }

# ── M4 spans ──────────────────────────────────────────────────────────────────────────────────────────────
def test_python_definition_spans_collapse_nested_and_include_decorators():
    spans = { s.qualname: ( s.start, s.end ) for s in X.python_definition_spans( BASE ) }
    assert spans[ "helper" ] == ( 5, 6 )
    assert spans[ "Widget" ][ 0 ] == 8
    assert spans[ "Widget.size" ] == ( 11, 15 ), "starts at the decorator, ends after the nested def's use"
    assert "Widget.size.inner" not in spans and "inner" not in spans
    assert spans[ "Widget.grow" ] == ( 17, 18 )
    assert spans[ "tail" ] == ( 20, 21 )
    assert X.site_for_line( X.python_definition_spans( BASE ), 13 ) == "Widget.size"   # inside the nested def
    assert X.site_for_line( X.python_definition_spans( BASE ), 9 ) == "Widget"         # class attribute
    assert X.site_for_line( X.python_definition_spans( BASE ), 3 ) == "<module>"

# ── M5–M7 sites and class ─────────────────────────────────────────────────────────────────────────────────
FILES = { "pkg/a.py": BASE, "pkg/b.py": BASE }

def test_two_hunks_in_one_function_are_one_site():
    p = diff( "pkg/a.py", [ ( "@@ -12,1 +12,1 @@", [ "-    def size(self):", "+    def size(self):  # x" ] ),
                            ( "@@ -15,1 +15,1 @@", [ "-        return inner(self._n)", "+        return inner(self._n) + 0" ] ) ] )
    r = X.sites_for_row( p, read_base( FILES ) )
    assert r.sites == { ( "pkg/a.py", "Widget.size" ) } and r.mclass == "ONE-SITE"

def test_two_functions_one_file_and_two_files():
    p = diff( "pkg/a.py", [ ( "@@ -6,1 +6,1 @@", [ "-    return x + 1", "+    return x + 2" ] ),
                            ( "@@ -21,1 +21,1 @@", [ "-    return LIMIT", "+    return LIMIT - 1" ] ) ] )
    r = X.sites_for_row( p, read_base( FILES ) )
    assert r.sites == { ( "pkg/a.py", "helper" ), ( "pkg/a.py", "tail" ) } and r.mclass == "MULTI-SITE-ONE-FILE"
    p2 = p + diff( "pkg/b.py", [ ( "@@ -3,1 +3,1 @@", [ "-LIMIT = 3", "+LIMIT = 4" ] ) ] )
    r2 = X.sites_for_row( p2, read_base( FILES ) )
    assert ( "pkg/b.py", "<module>" ) in r2.sites and r2.mclass == "MULTI-FILE"

def test_tests_docs_generated_are_not_sites_and_test_only_is_its_own_bucket():
    fix = diff( "pkg/a.py", [ ( "@@ -6,1 +6,1 @@", [ "-    return x + 1", "+    return x + 2" ] ) ] )
    extras = diff( "tests/test_a.py", [ ( "@@ -1,1 +1,2 @@", [ " x", "+y" ] ) ] ) \
           + diff( "docs/guide.rst", [ ( "@@ -1,1 +1,1 @@", [ "-a", "+b" ] ) ] ) \
           + diff( "app/migrations/0009_x.py", [ ( "@@ -1,1 +1,1 @@", [ "-a", "+b" ] ) ] )
    r = X.sites_for_row( fix + extras, read_base( FILES ) )
    assert r.sites == { ( "pkg/a.py", "helper" ) } and r.mclass == "ONE-SITE"
    assert r.buckets[ "TEST" ] == 1 and r.buckets[ "DOC" ] == 1 and r.buckets[ "GENERATED" ] == 1
    only_test = X.sites_for_row( diff( "tests/test_a.py", [ ( "@@ -1,1 +1,2 @@", [ " x", "+y" ] ) ] ), read_base( FILES ) )
    assert only_test.mclass == "TEST-ONLY"
    only_doc = X.sites_for_row( diff( "README.md", [ ( "@@ -1,1 +1,1 @@", [ "-a", "+b" ] ) ] ), read_base( FILES ) )
    assert only_doc.mclass == "NON-CODE"

def test_pure_insertion_of_a_method_lands_on_its_class_and_new_file_is_not_a_site():
    ins = diff( "pkg/a.py", [ ( "@@ -18,1 +18,4 @@", [ "         self._n = n", "+", "+    def shrink(self):", "+        self._n = 0" ] ) ] )
    r = X.sites_for_row( ins, read_base( FILES ) )
    assert r.sites == { ( "pkg/a.py", "Widget.grow" ) }, "anchor = the old line preceding the insertion (last line of grow)"
    ins2 = diff( "pkg/a.py", [ ( "@@ -16,1 +16,3 @@", [ "", "+    def extra(self):", "+        return 0" ] ) ] )   # blank line 16 sits between two methods
    r2 = X.sites_for_row( ins2, read_base( FILES ) )
    assert r2.sites == { ( "pkg/a.py", "Widget" ) }, "class-body level, outside any method"
    ins3 = diff( "pkg/a.py", [ ( "@@ -19,1 +19,3 @@", [ "", "+def extra():", "+    return 0" ] ) ] )   # blank line 19 is after the class's last statement
    r3m = X.sites_for_row( ins3, read_base( FILES ) )
    assert r3m.sites == { ( "pkg/a.py", "<module>" ) }, "ast ends the class at its last statement; a new top-level def lands on <module>"
    newf = "diff --git a/pkg/c.py b/pkg/c.py\nnew file mode 100644\n--- /dev/null\n+++ b/pkg/c.py\n@@ -0,0 +1,2 @@\n+def z():\n+    pass\n"
    r3 = X.sites_for_row( newf, read_base( FILES ) )
    assert r3.sites == set() and "new_file" in r3.flags and r3.mclass == "NON-CODE"

def test_otherlang_unparsed_rename_only_flags():
    c = diff( "ext/fast.c", [ ( "@@ -1,1 +1,1 @@", [ "-int a;", "+int b;" ] ) ] )
    r = X.sites_for_row( c, read_base( { "ext/fast.c": "int a;\n" } ) )
    assert r.sites == { ( "ext/fast.c", "<file>" ) } and "otherlang" in r.flags
    bad = diff( "pkg/bad.py", [ ( "@@ -1,1 +1,1 @@", [ "-def (:", "+def f():" ] ) ] )
    r2 = X.sites_for_row( bad, read_base( { "pkg/bad.py": "def (:\n" } ) )
    assert r2.sites == { ( "pkg/bad.py", "<unparsed>" ) } and "unparsed" in r2.flags
    ren = diff( "pkg/old.py", [], new_path="pkg/new.py", rename=True )
    r3 = X.sites_for_row( ren, read_base( FILES ) )
    assert r3.sites == set() and "rename_only" in r3.flags

def test_move_detection_needs_three_lines_and_another_file():
    body = [ "-def helper(x):", "-    y = x", "-    return y + 1" ]
    p = diff( "pkg/a.py", [ ( "@@ -5,3 +5,0 @@", body ) ] ) \
      + diff( "pkg/b.py", [ ( "@@ -21,0 +22,3 @@", [ l.replace( "-", "+", 1 ) for l in body ] ) ] )
    assert X.detect_moves( X.parse_patch( p ) )
    same_file = diff( "pkg/a.py", [ ( "@@ -5,3 +5,0 @@", body ), ( "@@ -21,0 +22,3 @@", [ l.replace( "-", "+", 1 ) for l in body ] ) ] )
    assert not X.detect_moves( X.parse_patch( same_file ) ), "a move inside one file is not flagged (both ends are sites anyway)"
    short = diff( "pkg/a.py", [ ( "@@ -5,2 +5,0 @@", body[ :2 ] ) ] ) + diff( "pkg/b.py", [ ( "@@ -1,0 +1,2 @@", [ l.replace( "-", "+", 1 ) for l in body[ :2 ] ] ) ] )
    assert not X.detect_moves( X.parse_patch( short ) )

# ── M8 ────────────────────────────────────────────────────────────────────────────────────────────────────
def test_spell_and_jaccard_match_locbench_spelling():
    assert X.spell( { ( "pkg/a.py", "Widget.size" ) } ) == { "pkg/a.py:Widget.size" }
    assert X.jaccard( { "a", "b" }, { "b", "c" } ) == 1 / 3.0 and X.jaccard( set(), set() ) == 1.0

# ── R1 sampler ────────────────────────────────────────────────────────────────────────────────────────────
def test_stratified_systematic_sample_is_deterministic_and_floored():
    strata = { "ONE-SITE": [ "r%03d" % i for i in range( 250 ) ], "MULTI-FILE": [ "m%02d" % i for i in range( 30 ) ] }
    s = X.stratified_systematic_sample( strata )
    assert len( s[ "ONE-SITE" ] ) == 42 and s[ "ONE-SITE" ][ :2 ] == [ "r000", "r006" ], "k = 250 // 40 = 6"
    assert s[ "MULTI-FILE" ] == sorted( strata[ "MULTI-FILE" ] ), "a stratum below the floor is taken whole"
    assert X.stratified_systematic_sample( { "x": list( reversed( strata[ "ONE-SITE" ] ) ) } )[ "x" ] == s[ "ONE-SITE" ], "order-independent"

# ── R6/R7 labels and kappa ────────────────────────────────────────────────────────────────────────────────
def test_row_label_and_kappa():
    assert X.row_label( "CROSS", "CROSS" ) == "CROSS" and X.row_label( "LOCAL", "LOCAL" ) == "LOCAL"
    assert X.row_label( "CROSS", "LOCAL" ) == ( "UNTAGGED", "DISAGREE" )
    assert X.row_label( "CROSS", "NOT-A-DEFECT" ) == ( "UNTAGGED", "NOT-A-DEFECT" )
    assert X.row_label( "UNDECIDED", "LOCAL" ) == ( "UNTAGGED", "UNDECIDED" )
    a = [ "CROSS", "LOCAL", "CROSS", "LOCAL" ]
    assert X.cohen_kappa( a, a ) == 1.0
    assert abs( X.cohen_kappa( a, [ "CROSS", "CROSS", "LOCAL", "LOCAL" ] ) ) < 1e-12, "chance agreement is 0"
    assert X.cohen_kappa( [ "CROSS" ] * 4, [ "CROSS" ] * 4 ) == 1.0
    assert X.kappa_verdict( 0.61 ) == "quotable" and X.kappa_verdict( 0.5 ) == "moderate" and X.kappa_verdict( 0.39 ) == "failed"

# ── §7 estimators ─────────────────────────────────────────────────────────────────────────────────────────
def test_wilson_pins_the_internal_comparator():
    lo, hi = X.wilson( 149, 169 )
    assert round( lo, 3 ) == 0.824 and round( hi, 3 ) == 0.922, ( lo, hi )
    c = X.internal_comparator()
    assert c[ "rows" ] == 377 and c[ "usable" ] == 292 and c[ "tagged" ] == 169 and c[ "untagged" ] == 123
    assert c[ "cross" ] == 149 and c[ "local" ] == 20 and round( c[ "rate" ], 3 ) == 0.882
    assert X.wilson( 0, 0 ) == ( 0.0, 0.0 )

def test_post_stratified_estimate_weights_by_manifest_and_is_reproducible():
    strata = { "ONE-SITE": dict( N=300, labels=[ "CROSS" ] * 10 + [ "LOCAL" ] * 30 ),
               "MULTI-FILE": dict( N=100, labels=[ "CROSS" ] * 30 + [ "LOCAL" ] * 10 ),
               "MULTI-SITE-ONE-FILE": dict( N=50, labels=[] ) }
    e = X.post_stratified_estimate( strata, resamples=200 )
    assert abs( e[ "point" ] - ( 0.75 * 0.25 + 0.25 * 0.75 ) ) < 1e-12, "weights from N, rates from the sample; the empty stratum is dropped and named"
    assert e[ "dropped" ] == [ "MULTI-SITE-ONE-FILE" ]
    assert e[ "lo" ] <= e[ "point" ] <= e[ "hi" ]
    assert X.post_stratified_estimate( strata, resamples=200 ) == e, "same seed, same interval"
    allc = X.post_stratified_estimate( { "s": dict( N=10, labels=[ "CROSS" ] * 5 ) }, resamples=50 )
    assert allc[ "point" ] == 1.0 and allc[ "lo" ] == 1.0 and allc[ "hi" ] == 1.0

# ── §9 decision ───────────────────────────────────────────────────────────────────────────────────────────
def test_decision_table_uses_the_frozen_anchors():
    assert X.decision( 0.30, 0.50, 0.7, 0.3 )[ 0 ] == "STARK"
    assert X.decision( 0.30, 0.51, 0.7, 0.3 )[ 0 ] == "INDETERMINATE"
    assert X.decision( 0.60, 0.80, 0.7, 0.3 )[ 0 ] == "THIN"
    assert X.decision( 0.59, 0.80, 0.7, 0.3 )[ 0 ] == "INDETERMINATE"
    assert X.decision( 0.30, 0.45, 0.59, 0.3 ) == ( "INDETERMINATE", "binary kappa 0.59 below 0.60 (R7)" )
    assert X.decision( 0.30, 0.45, 0.9, 0.51 )[ 0 ] == "INDETERMINATE"
    assert X.decision( 0.30, 0.45, 0.9, 0.3, fingerprint_ok=False ) == ( "INDETERMINATE", "fingerprint failed (§4.4)" )
    assert X.decision( 0.30, 0.45, 0.9, 0.3, m8_ok=False )[ 0 ] == "INDETERMINATE"
    assert X.decision( None, None, 0.9, 0.3 )[ 0 ] == "INDETERMINATE"

def test_frozen_constants_are_the_registered_ones():
    F = X.FROZEN
    assert F[ "rows_json_sha256" ] == "5bbcea4bff11396f38f8aca3e64d697a8ea1da2bc54d705da7f6e34886804c97"
    assert ( F[ "per_stratum_floor" ], F[ "kappa_floor" ], F[ "kappa_moderate" ] ) == ( 40, 0.60, 0.40 )
    assert ( F[ "stark_hi" ], F[ "thin_lo" ], F[ "untagged_ceiling" ] ) == ( 0.50, 0.60, 0.50 )
    assert ( F[ "bootstrap_seed" ], F[ "bootstrap_resamples" ], F[ "move_min_lines" ] ) == ( 20260923, 2000, 3 )
    assert ( F[ "m8_jaccard_floor" ], F[ "unavailable_floor" ] ) == ( 0.70, 0.05 )

def test_manifest_hash_is_over_exact_lines():
    assert X.manifest_hash( [ "a\tb", "c\td" ] ) == X.manifest_hash( [ "a\tb", "c\td" ] )
    assert X.manifest_hash( [ "a\tb" ] ) != X.manifest_hash( [ "a\tc" ] )

def test_main_refuses_an_unpinned_rows_file( tmp=None ):
    import tempfile
    d = tempfile.mkdtemp()
    rows = os.path.join( d, "rows.json" )
    open( rows, "w" ).write( "[]" )
    rc = X.main( [ "--rows", rows, "--repos-dir", d, "--out", os.path.join( d, "out" ) ] )
    assert rc == 2, "an arbitrary rows file must be refused before anything is read (§4.1)"
    assert not os.path.exists( os.path.join( d, "out" ) )


def main():
    tests = [ ( n, f ) for n, f in sorted( globals().items() ) if n.startswith( "test_" ) and callable( f ) ]
    failed = 0
    for name, fn in tests:
        try:
            fn()
            print( "  PASS  %s" % name )
        except Exception as e:                       # report every failure, not just the first
            failed += 1
            print( "  FAIL  %s: %s: %s" % ( name, type( e ).__name__, e ) )
    print( "%d/%d passed" % ( len( tests ) - failed, len( tests ) ) )
    return 1 if failed else 0

if __name__ == "__main__":
    sys.exit( main() )
